from category import Category
from family import Family
from variant import Affix, Variant

FAMILIES: list[Family] = [
    # Building Blocks
    # Wood
    Family(Category.BUILDING_BLOCKS, "OAK", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_OAK", 1),
    Family(Category.BUILDING_BLOCKS, "SPRUCE", 2),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_SPRUCE", 3),
    Family(Category.BUILDING_BLOCKS, "BIRCH", 4),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_BIRCH", 5),
    Family(Category.BUILDING_BLOCKS, "JUNGLE", 6),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_JUNGLE", 7),
    Family(Category.BUILDING_BLOCKS, "ACACIA", 8),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_ACACIA", 9),
    Family(Category.BUILDING_BLOCKS, "DARK_OAK", 10),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_DARK_OAK", 11),
    Family(Category.BUILDING_BLOCKS, "MANGROVE", 12),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_MANGROVE", 13),
    Family(Category.BUILDING_BLOCKS, "CHERRY", 14),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_CHERRY", 15),
    Family(Category.BUILDING_BLOCKS, "PALE_OAK", 16),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_PALE_OAK", 17),
    # Bamboo
    Family(Category.BUILDING_BLOCKS, "BAMBOO", 18),
    Family(Category.BUILDING_BLOCKS, "BAMBOO_BLOCK", 19),
    Family(Category.BUILDING_BLOCKS, "BAMBOO_MOSAIC", 20),
    # Nether Wood
    Family(Category.BUILDING_BLOCKS, "CRIMSON", 21),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_CRIMSON", 22),
    Family(Category.BUILDING_BLOCKS, "WARPED", 23),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_WARPED", 24),
    # Stone
    Family(Category.BUILDING_BLOCKS, "STONE", 25),
    Family(Category.BUILDING_BLOCKS, "COBBLESTONE", 26),
    Family(Category.BUILDING_BLOCKS, "MOSSY_COBBLESTONE", 27),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_STONE", 28),
    Family(Category.BUILDING_BLOCKS, "STONE_BRICKS", 29),
    Family(Category.BUILDING_BLOCKS, "STONE_BRICK", 30),
    Family(Category.BUILDING_BLOCKS, "MOSSY_STONE_BRICKS", 31),
    Family(Category.BUILDING_BLOCKS, "MOSSY_STONE_BRICK", 32),
    Family(Category.BUILDING_BLOCKS, "GRANITE", 33),
    Family(Category.BUILDING_BLOCKS, "POLISHED_GRANITE", 34),
    Family(Category.BUILDING_BLOCKS, "DIORITE", 35),
    Family(Category.BUILDING_BLOCKS, "POLISHED_DIORITE", 36),
    Family(Category.BUILDING_BLOCKS, "ANDESITE", 37),
    Family(Category.BUILDING_BLOCKS, "POLISHED_ANDESITE", 38),
    # Deepslate
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE", 39),
    Family(Category.BUILDING_BLOCKS, "COBBLED_DEEPSLATE", 40),
    Family(Category.BUILDING_BLOCKS, "CHISELED_DEEPSLATE", 41),
    Family(Category.BUILDING_BLOCKS, "POLISHED_DEEPSLATE", 42),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_BRICKS", 43),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_BRICK", 44),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_TILES", 45),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_TILE", 46),
    Family(Category.BUILDING_BLOCKS, "REINFORCED_DEEPSLATE", 47),
    # Tuff
    Family(Category.BUILDING_BLOCKS, "TUFF", 48),
    Family(Category.BUILDING_BLOCKS, "CHISELED_TUFF", 49),
    Family(Category.BUILDING_BLOCKS, "POLISHED_TUFF", 50),
    Family(Category.BUILDING_BLOCKS, "TUFF_BRICKS", 51),
    Family(Category.BUILDING_BLOCKS, "TUFF_BRICK", 52),
    Family(Category.BUILDING_BLOCKS, "CHISELED_TUFF_BRICKS", 53),
    # Bricks
    Family(Category.BUILDING_BLOCKS, "BRICKS", 54),
    Family(Category.BUILDING_BLOCKS, "BRICK", 55),
    Family(Category.BUILDING_BLOCKS, "PACKED_MUD", 56),
    Family(Category.BUILDING_BLOCKS, "MUD_BRICKS", 57),
    Family(Category.BUILDING_BLOCKS, "MUD_BRICK", 58),
    Family(Category.BUILDING_BLOCKS, "RESIN_BRICKS", 59),
    Family(Category.BUILDING_BLOCKS, "RESIN_BRICK", 60),
    # Sand
    Family(Category.BUILDING_BLOCKS, "SANDSTONE", 61),
    Family(Category.BUILDING_BLOCKS, "CHISELED_SANDSTONE", 62),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_SANDSTONE", 63),
    Family(Category.BUILDING_BLOCKS, "CUT_SANDSTONE", 64),
    Family(Category.BUILDING_BLOCKS, "RED_SANDSTONE", 65),
    Family(Category.BUILDING_BLOCKS, "CHISELED_RED_SANDSTONE", 66),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_RED_SANDSTONE", 67),
    Family(Category.BUILDING_BLOCKS, "CUT_RED_SANDSTONE", 68),
    # Cinnabar
    Family(Category.BUILDING_BLOCKS, "CINNABAR", 69),
    Family(Category.BUILDING_BLOCKS, "CHISELED_CINNABAR", 70),
    Family(Category.BUILDING_BLOCKS, "POLISHED_CINNABAR", 71),
    Family(Category.BUILDING_BLOCKS, "CINNABAR_BRICKS", 72),
    Family(Category.BUILDING_BLOCKS, "CINNABAR_BRICK", 73),
    # Sulfur
    Family(Category.BUILDING_BLOCKS, "SULFUR", 74),
    Family(Category.BUILDING_BLOCKS, "POLISHED_SULFUR", 75),
    Family(Category.BUILDING_BLOCKS, "SULFUR_BRICKS", 76),
    Family(Category.BUILDING_BLOCKS, "SULFUR_BRICK", 77),
    # Ocean
    Family(Category.BUILDING_BLOCKS, "SEA_LANTERN", 78),
    Family(Category.BUILDING_BLOCKS, "PRISMARINE", 79),
    Family(Category.BUILDING_BLOCKS, "PRISMARINE_BRICKS", 80),
    Family(Category.BUILDING_BLOCKS, "PRISMARINE_BRICK", 81),
    Family(Category.BUILDING_BLOCKS, "DARK_PRISMARINE", 82),
    # Nether
    Family(Category.BUILDING_BLOCKS, "NETHERRACK", 83),
    Family(Category.BUILDING_BLOCKS, "NETHER_BRICKS", 84),
    Family(Category.BUILDING_BLOCKS, "NETHER_BRICK", 85),
    Family(Category.BUILDING_BLOCKS, "RED_NETHER_BRICK", 86),
    Family(Category.BUILDING_BLOCKS, "BASALT", 87),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_BASALT", 88),
    Family(Category.BUILDING_BLOCKS, "POLISHED_BASALT", 89),
    Family(Category.BUILDING_BLOCKS, "BLACKSTONE", 90),
    Family(Category.BUILDING_BLOCKS, "GILDED_BLACKSTONE", 91),
    Family(Category.BUILDING_BLOCKS, "POLISHED_BLACKSTONE", 92),
    Family(Category.BUILDING_BLOCKS, "POLISHED_BLACKSTONE_BRICKS", 93),
    Family(Category.BUILDING_BLOCKS, "POLISHED_BLACKSTONE_BRICK", 94),
    # End
    Family(Category.BUILDING_BLOCKS, "END_STONE", 95),
    Family(Category.BUILDING_BLOCKS, "END_STONE_BRICKS", 96),
    Family(Category.BUILDING_BLOCKS, "END_STONE_BRICK", 97),
    Family(Category.BUILDING_BLOCKS, "PURPUR", 98),
    # Minerals
    Family(Category.BUILDING_BLOCKS, "COAL", 99),
    Family(Category.BUILDING_BLOCKS, "IRON", 100),
    Family(Category.BUILDING_BLOCKS, "HEAVY_WEIGHTED_PRESSURE_PLATE", 101),
    Family(Category.BUILDING_BLOCKS, "GOLD", 102),
    Family(Category.BUILDING_BLOCKS, "LIGHT_WEIGHTED_PRESSURE_PLATE", 103),
    Family(Category.BUILDING_BLOCKS, "REDSTONE", 104),
    Family(Category.BUILDING_BLOCKS, "EMERALD", 105),
    Family(Category.BUILDING_BLOCKS, "LAPIS", 106),
    Family(Category.BUILDING_BLOCKS, "DIAMOND", 107),
    Family(Category.BUILDING_BLOCKS, "NETHERITE", 108),
    Family(Category.BUILDING_BLOCKS, "QUARTZ", 109),
    Family(Category.BUILDING_BLOCKS, "QUARTZ_BRICKS", 110),
    Family(Category.BUILDING_BLOCKS, "QUARTZ_BRICK", 111),
    Family(Category.BUILDING_BLOCKS, "AMETHYST", 112),
    # Copper
    Family(Category.BUILDING_BLOCKS, "COPPER", 113),
    Family(Category.BUILDING_BLOCKS, "CHISELED_COPPER", 114),
    Family(Category.BUILDING_BLOCKS, "COPPER_GRATE", 115),
    Family(Category.BUILDING_BLOCKS, "CUT_COPPER", 116),
    Family(Category.BUILDING_BLOCKS, "WEATHERED_CUT_COPPER", 117),
    Family(Category.BUILDING_BLOCKS, "COPPER_BARS", 118),
    Family(Category.BUILDING_BLOCKS, "COPPER_DOOR", 119),
    Family(Category.BUILDING_BLOCKS, "COPPER_TRAPDOOR", 120),
    Family(Category.BUILDING_BLOCKS, "COPPER_BULB", 121),
    Family(Category.BUILDING_BLOCKS, "COPPER_CHAIN", 122),
    Family(Category.BUILDING_BLOCKS, "WAXED_COPPER", 123),
    Family(Category.BUILDING_BLOCKS, "WAXED_EXPOSED_COPPER", 124),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_COPPER", 125),
    Family(Category.BUILDING_BLOCKS, "WAXED_OXIDIZED_COPPER", 126),
    Family(Category.BUILDING_BLOCKS, "WAXED_CUT_COPPER", 127),
    Family(Category.BUILDING_BLOCKS, "WAXED_EXPOSED_CUT_COPPER", 128),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_CUT_COPPER", 129),
    Family(Category.BUILDING_BLOCKS, "WAXED_OXIDIZED_CUT_COPPER", 130),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_CHISELED_COPPER", 131),
    # Colored Blocks
    Family(Category.COLORED_BLOCKS, "WOOL", 0),
    Family(Category.COLORED_BLOCKS, "CARPET", 1),
    Family(Category.COLORED_BLOCKS, "TERRACOTTA", 2),
    Family(Category.COLORED_BLOCKS, "CONCRETE", 3),
    Family(Category.COLORED_BLOCKS, "CONCRETE_POWDER", 4),
    Family(Category.COLORED_BLOCKS, "GLAZED_TERRACOTTA", 5),
    Family(Category.COLORED_BLOCKS, "GLASS", 6),
    Family(Category.COLORED_BLOCKS, "TINTED_GLASS", 7),
    Family(Category.COLORED_BLOCKS, "STAINED_GLASS", 8),
    Family(Category.COLORED_BLOCKS, "GLASS_PANE", 9),
    Family(Category.COLORED_BLOCKS, "STAINED_GLASS_PANE", 10),
    Family(Category.COLORED_BLOCKS, "SHULKER_BOX", 11),
    Family(Category.COLORED_BLOCKS, "BED", 12),
    Family(Category.COLORED_BLOCKS, "CANDLE", 13),
    Family(Category.COLORED_BLOCKS, "BANNER", 14),
    # Natural Blocks
    Family(Category.NATURAL_BLOCKS, "GRASS", 0),
    Family(Category.NATURAL_BLOCKS, "PODZOL", 1),
    Family(Category.NATURAL_BLOCKS, "MYCELIUM", 2),
    Family(Category.NATURAL_BLOCKS, "DIRT_PATH", 3),
    Family(Category.NATURAL_BLOCKS, "DIRT", 4),
    Family(Category.NATURAL_BLOCKS, "COARSE_DIRT", 5),
    Family(Category.NATURAL_BLOCKS, "ROOTED_DIRT", 6),
    Family(Category.NATURAL_BLOCKS, "FARMLAND", 7),
    Family(Category.NATURAL_BLOCKS, "MUD", 8),
    Family(Category.NATURAL_BLOCKS, "CLAY", 9),
    Family(Category.NATURAL_BLOCKS, "GRAVEL", 10),
    Family(Category.NATURAL_BLOCKS, "SAND", 11),
    Family(Category.NATURAL_BLOCKS, "RED_SAND", 12),
    Family(Category.NATURAL_BLOCKS, "ICE", 13),
    Family(Category.NATURAL_BLOCKS, "PACKED_ICE", 14),
    Family(Category.NATURAL_BLOCKS, "BLUE_ICE", 15),
    Family(Category.NATURAL_BLOCKS, "SNOW_BLOCK", 16),
    Family(Category.NATURAL_BLOCKS, "SNOW", 17),
    Family(Category.NATURAL_BLOCKS, "MOSS", 18),
    Family(Category.NATURAL_BLOCKS, "MOSS_CARPET", 19),
    Family(Category.NATURAL_BLOCKS, "PALE_MOSS", 20),
    Family(Category.NATURAL_BLOCKS, "PALE_MOSS_CARPET", 21),
    Family(Category.NATURAL_BLOCKS, "PALE_HANGING_MOSS", 22),
    Family(Category.NATURAL_BLOCKS, "CALCITE", 23),
    Family(Category.NATURAL_BLOCKS, "DRIPSTONE", 24),
    Family(Category.NATURAL_BLOCKS, "POINTED_DRIPSTONE", 25),
    Family(Category.NATURAL_BLOCKS, "SULFUR_SPIKE", 26),
    Family(Category.NATURAL_BLOCKS, "POTENT_SULFUR", 27),
    Family(Category.NATURAL_BLOCKS, "MAGMA", 28),
    Family(Category.NATURAL_BLOCKS, "OBSIDIAN", 29),
    Family(Category.NATURAL_BLOCKS, "CRYING_OBSIDIAN", 30),
    Family(Category.NATURAL_BLOCKS, "CRIMSON_NYLIUM", 31),
    Family(Category.NATURAL_BLOCKS, "WARPED_NYLIUM", 32),
    Family(Category.NATURAL_BLOCKS, "SOUL_SAND", 33),
    Family(Category.NATURAL_BLOCKS, "SOUL_SOIL", 34),
    Family(Category.NATURAL_BLOCKS, "BONE", 35),
    Family(Category.NATURAL_BLOCKS, "COAL_ORE", 36),
    Family(Category.NATURAL_BLOCKS, "IRON_ORE", 37),
    Family(Category.NATURAL_BLOCKS, "COPPER_ORE", 38),
    Family(Category.NATURAL_BLOCKS, "GOLD_ORE", 39),
    Family(Category.NATURAL_BLOCKS, "REDSTONE_ORE", 40),
    Family(Category.NATURAL_BLOCKS, "EMERALD_ORE", 41),
    Family(Category.NATURAL_BLOCKS, "LAPIS_ORE", 42),
    Family(Category.NATURAL_BLOCKS, "DIAMOND_ORE", 43),
    Family(Category.NATURAL_BLOCKS, "ANCIENT_DEBRIS", 44),
    Family(Category.NATURAL_BLOCKS, "RAW_IRON", 45),
    Family(Category.NATURAL_BLOCKS, "RAW_COPPER", 46),
    Family(Category.NATURAL_BLOCKS, "RAW_GOLD", 47),
    Family(Category.NATURAL_BLOCKS, "GLOWSTONE", 48),
    Family(Category.NATURAL_BLOCKS, "BUDDING_AMETHYST", 49),
    Family(Category.NATURAL_BLOCKS, "SMALL_AMETHYST_BUD", 50),
    Family(Category.NATURAL_BLOCKS, "MEDIUM_AMETHYST_BUD", 51),
    Family(Category.NATURAL_BLOCKS, "LARGE_AMETHYST_BUD", 52),
    Family(Category.NATURAL_BLOCKS, "AMETHYST_CLUSTER", 53),
    Family(Category.NATURAL_BLOCKS, "MANGROVE_ROOTS", 54),
    Family(Category.NATURAL_BLOCKS, "MUDDY_MANGROVE", 55),
    Family(Category.NATURAL_BLOCKS, "LEAVES", 56),
    Family(Category.NATURAL_BLOCKS, "BROWN_MUSHROOM", 57),
    Family(Category.NATURAL_BLOCKS, "RED_MUSHROOM", 58),
    Family(Category.NATURAL_BLOCKS, "NETHER_WART", 59),
    Family(Category.NATURAL_BLOCKS, "WARPED_WART", 60),
    Family(Category.NATURAL_BLOCKS, "SHROOMLIGHT", 61),
    Family(Category.NATURAL_BLOCKS, "SAPLING", 62),
    Family(Category.NATURAL_BLOCKS, "AZALEA", 63),
    Family(Category.NATURAL_BLOCKS, "FLOWERING_AZALEA", 64),
    Family(Category.NATURAL_BLOCKS, "MUSHROOM", 65),
    Family(Category.NATURAL_BLOCKS, "CRIMSON_FUNGUS", 66),
    Family(Category.NATURAL_BLOCKS, "WARPED_FUNGUS", 67),
    Family(Category.NATURAL_BLOCKS, "SHORT_GRASS", 68),
    Family(Category.NATURAL_BLOCKS, "FERN", 69),
    Family(Category.NATURAL_BLOCKS, "SHORT_DRY_GRASS", 70),
    Family(Category.NATURAL_BLOCKS, "BUSH", 71),
    Family(Category.NATURAL_BLOCKS, "DEAD_BUSH", 72),
    Family(Category.NATURAL_BLOCKS, "SUGAR_CANE", 73),
    Family(Category.NATURAL_BLOCKS, "CACTUS", 74),
    Family(Category.NATURAL_BLOCKS, "CRIMSON_ROOTS", 75),
    Family(Category.NATURAL_BLOCKS, "WARPED_ROOTS", 76),
    Family(Category.NATURAL_BLOCKS, "NETHER_SPROUTS", 77),
    Family(Category.NATURAL_BLOCKS, "WEEPING_VINES", 78),
    Family(Category.NATURAL_BLOCKS, "TWISTING_VINES", 79),
    Family(Category.NATURAL_BLOCKS, "VINES", 80),
    Family(Category.NATURAL_BLOCKS, "TALL_GRASS", 81),
    Family(Category.NATURAL_BLOCKS, "LARGE_FERN", 82),
    Family(Category.NATURAL_BLOCKS, "TALL_DRY_GRASS", 83),
    Family(Category.NATURAL_BLOCKS, "SUNFLOWER", 84),
    Family(Category.NATURAL_BLOCKS, "LILAC", 85),
    Family(Category.NATURAL_BLOCKS, "ROSE_BUSH", 86),
    Family(Category.NATURAL_BLOCKS, "PEONY", 87),
    Family(Category.NATURAL_BLOCKS, "PITCHER_PLANT", 88),
    Family(Category.NATURAL_BLOCKS, "BIG_DRIPLEAF", 89),
    Family(Category.NATURAL_BLOCKS, "SMALL_DRIPLEAF", 90),
    Family(Category.NATURAL_BLOCKS, "CHORUS_PLANT", 91),
    Family(Category.NATURAL_BLOCKS, "CHORUS_FLOWER", 92),
    Family(Category.NATURAL_BLOCKS, "GLOW_LICHEN", 93),
    Family(Category.NATURAL_BLOCKS, "HANGING_ROOTS", 94),
    Family(Category.NATURAL_BLOCKS, "FROGSPAWN", 95),
    Family(Category.NATURAL_BLOCKS, "TURTLE_EGG", 96),
    Family(Category.NATURAL_BLOCKS, "SNIFFER_EGG", 97),
    Family(Category.NATURAL_BLOCKS, "HAPPY_GHAST", 98),
    Family(Category.NATURAL_BLOCKS, "WHEAT_SEEDS", 99),
    Family(Category.NATURAL_BLOCKS, "COCOA_BEANS", 100),
    Family(Category.NATURAL_BLOCKS, "PUMPKIN_SEEDS", 101),
    Family(Category.NATURAL_BLOCKS, "MELON_SEEDS", 102),
    Family(Category.NATURAL_BLOCKS, "BEETROOT_SEEDS", 103),
    Family(Category.NATURAL_BLOCKS, "TORCHFLOWER_SEEDS", 104),
    Family(Category.NATURAL_BLOCKS, "PITCHER_POD", 105),
    Family(Category.NATURAL_BLOCKS, "GLOW_BERRIES", 106),
    Family(Category.NATURAL_BLOCKS, "SWEET_BERRIES", 107),
    Family(Category.NATURAL_BLOCKS, "NETHER_WART", 108),
    Family(Category.NATURAL_BLOCKS, "LILY_PAD", 109),
    Family(Category.NATURAL_BLOCKS, "SEAGRASS", 110),
    Family(Category.NATURAL_BLOCKS, "SEA_PICKLE", 111),
    Family(Category.NATURAL_BLOCKS, "KELP", 112),
    Family(Category.NATURAL_BLOCKS, "DRIED_KELP", 113),
    Family(Category.NATURAL_BLOCKS, "CORAL_BLOCK", 114),
    Family(Category.NATURAL_BLOCKS, "CORAL", 115),
    Family(Category.NATURAL_BLOCKS, "CORAL_FAN", 116),
    Family(Category.NATURAL_BLOCKS, "SPONGE", 117),
    Family(Category.NATURAL_BLOCKS, "WET_SPONGE", 118),
    Family(Category.NATURAL_BLOCKS, "MELON", 119),
    Family(Category.NATURAL_BLOCKS, "PUMPKIN", 120),
    Family(Category.NATURAL_BLOCKS, "CARVED_PUMPKIN", 121),
    Family(Category.NATURAL_BLOCKS, "JACK_O_LANTERN", 122),
    Family(Category.NATURAL_BLOCKS, "HAY_BLOCK", 123),
    Family(Category.NATURAL_BLOCKS, "BEE_NEST", 124),
    Family(Category.NATURAL_BLOCKS, "HONEYCOMB_BLOCK", 125),
    Family(Category.NATURAL_BLOCKS, "SLIME", 126),
    Family(Category.NATURAL_BLOCKS, "HONEY", 127),
    Family(Category.NATURAL_BLOCKS, "RESIN", 128),
    Family(Category.NATURAL_BLOCKS, "FROGLIGHT", 129),
    Family(Category.NATURAL_BLOCKS, "SCULK", 130),
    Family(Category.NATURAL_BLOCKS, "SCULK_VEIN", 131),
    Family(Category.NATURAL_BLOCKS, "SCULK_CATALYST", 132),
    Family(Category.NATURAL_BLOCKS, "SCULK_SHRIEKER", 133),
    Family(Category.NATURAL_BLOCKS, "SCULK_SENSOR", 134),
    Family(Category.NATURAL_BLOCKS, "COBWEB", 135),
    Family(Category.NATURAL_BLOCKS, "BEDROCK", 136),
    # Functional Blocks
    Family(Category.FUNCTIONAL_BLOCKS, "TORCH", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "LANTERN", 1),
    Family(Category.FUNCTIONAL_BLOCKS, "CHAIN", 2),
    Family(Category.FUNCTIONAL_BLOCKS, "END_ROD", 3),
    Family(Category.FUNCTIONAL_BLOCKS, "CRAFTING_TABLE", 4),
    Family(Category.FUNCTIONAL_BLOCKS, "STONECUTTER", 5),
    Family(Category.FUNCTIONAL_BLOCKS, "CARTOGRAPHY_TABLE", 6),
    Family(Category.FUNCTIONAL_BLOCKS, "FLETCHING_TABLE", 7),
    Family(Category.FUNCTIONAL_BLOCKS, "SMITHING_TABLE", 8),
    Family(Category.FUNCTIONAL_BLOCKS, "GRINDSTONE", 9),
    Family(Category.FUNCTIONAL_BLOCKS, "LOOM", 10),
    Family(Category.FUNCTIONAL_BLOCKS, "FURNACE", 11),
    Family(Category.FUNCTIONAL_BLOCKS, "SMOKER", 12),
    Family(Category.FUNCTIONAL_BLOCKS, "BLAST_FURNACE", 13),
    Family(Category.FUNCTIONAL_BLOCKS, "CAMPFIRE", 14),
    Family(Category.FUNCTIONAL_BLOCKS, "SOUL_CAMPFIRE", 15),
    Family(Category.FUNCTIONAL_BLOCKS, "ANVIL", 16),
    Family(Category.FUNCTIONAL_BLOCKS, "COMPOSTER", 17),
    Family(Category.FUNCTIONAL_BLOCKS, "NOTE_BLOCK", 18),
    Family(Category.FUNCTIONAL_BLOCKS, "JUKEBOX", 19),
    Family(Category.FUNCTIONAL_BLOCKS, "ENCHANTING_TABLE", 20),
    Family(Category.FUNCTIONAL_BLOCKS, "END_CRYSTAL", 21),
    Family(Category.FUNCTIONAL_BLOCKS, "BREWING_STAND", 22),
    Family(Category.FUNCTIONAL_BLOCKS, "CAULDRON", 23),
    Family(Category.FUNCTIONAL_BLOCKS, "BELL", 24),
    Family(Category.FUNCTIONAL_BLOCKS, "BEACON", 25),
    Family(Category.FUNCTIONAL_BLOCKS, "CONDUIT", 26),
    Family(Category.FUNCTIONAL_BLOCKS, "LODESTONE", 27),
    Family(Category.FUNCTIONAL_BLOCKS, "LADDER", 28),
    Family(Category.FUNCTIONAL_BLOCKS, "SCAFFOLDING", 29),
    Family(Category.FUNCTIONAL_BLOCKS, "BEEHIVE", 30),
    Family(Category.FUNCTIONAL_BLOCKS, "SUSPICIOUS_SAND", 31),
    Family(Category.FUNCTIONAL_BLOCKS, "SUSPICIOUS_GRAVEL", 32),
    Family(Category.FUNCTIONAL_BLOCKS, "LIGHTNING_ROD", 33),
    Family(Category.FUNCTIONAL_BLOCKS, "FLOWER_POT", 34),
    Family(Category.FUNCTIONAL_BLOCKS, "DECORATED_POT", 35),
    Family(Category.FUNCTIONAL_BLOCKS, "ARMOR_STAND", 36),
    Family(Category.FUNCTIONAL_BLOCKS, "ITEM_FRAME", 37),
    Family(Category.FUNCTIONAL_BLOCKS, "GLOW_ITEM_FRAME", 38),
    Family(Category.FUNCTIONAL_BLOCKS, "PAINTING", 39),
    Family(Category.FUNCTIONAL_BLOCKS, "BOOKSHELF", 40),
    Family(Category.FUNCTIONAL_BLOCKS, "CHISELED_BOOKSHELF", 41),
    Family(Category.FUNCTIONAL_BLOCKS, "SHELF", 42),
    Family(Category.FUNCTIONAL_BLOCKS, "LECTERN", 43),
    Family(Category.FUNCTIONAL_BLOCKS, "SIGN", 44),
    Family(Category.FUNCTIONAL_BLOCKS, "HANGING_SIGN", 45),
    Family(Category.FUNCTIONAL_BLOCKS, "CHEST", 46),
    Family(Category.FUNCTIONAL_BLOCKS, "COPPER_CHEST", 47),
    Family(Category.FUNCTIONAL_BLOCKS, "BARREL", 48),
    Family(Category.FUNCTIONAL_BLOCKS, "ENDER_CHEST", 49),
    Family(Category.FUNCTIONAL_BLOCKS, "COPPER_GOLEM_STATUE", 50),
    Family(Category.FUNCTIONAL_BLOCKS, "SKULL", 51),
    Family(Category.FUNCTIONAL_BLOCKS, "HEAD", 52),
    Family(Category.FUNCTIONAL_BLOCKS, "INFESTED", 53),
    Family(Category.FUNCTIONAL_BLOCKS, "DRAGON_EGG", 54),
    Family(Category.FUNCTIONAL_BLOCKS, "END_PORTAL_FRAME", 55),
    Family(Category.FUNCTIONAL_BLOCKS, "VAULT", 56),
    Family(Category.FUNCTIONAL_BLOCKS, "ENDER_EYE", 57),
    # Redstone
    Family(Category.REDSTONE_BLOCKS, "REDSTONE", 0),
    Family(Category.REDSTONE_BLOCKS, "REPEATER", 1),
    Family(Category.REDSTONE_BLOCKS, "COMPARATOR", 2),
    Family(Category.REDSTONE_BLOCKS, "TARGET", 3),
    Family(Category.REDSTONE_BLOCKS, "LEVER", 4),
    Family(Category.REDSTONE_BLOCKS, "CALIBRATED_SCULK_SENSOR", 5),
    Family(Category.REDSTONE_BLOCKS, "TRIPWIRE_HOOK", 6),
    Family(Category.REDSTONE_BLOCKS, "DAYLIGHT_DETECTOR", 7),
    Family(Category.REDSTONE_BLOCKS, "PISTON", 8),
    Family(Category.REDSTONE_BLOCKS, "STICKY_PISTON", 9),
    Family(Category.REDSTONE_BLOCKS, "DISPENSER", 10),
    Family(Category.REDSTONE_BLOCKS, "DROPPER", 11),
    Family(Category.REDSTONE_BLOCKS, "CRAFTER", 12),
    Family(Category.REDSTONE_BLOCKS, "HOPPER", 13),
    Family(Category.REDSTONE_BLOCKS, "TRAPPED_CHEST", 14),
    Family(Category.REDSTONE_BLOCKS, "OBSERVER", 15),
    Family(Category.REDSTONE_BLOCKS, "RAIL", 16),
    Family(Category.REDSTONE_BLOCKS, "MINECART", 17),
    Family(Category.REDSTONE_BLOCKS, "TNT", 18),
    Family(Category.REDSTONE_BLOCKS, "REDSTONE_LAMP", 19),
    # --- MANUALLY REVIEWED ---------------------------------------------------
    Family(Category.NATURAL_BLOCKS, "CANDLE_CAKE", 0),
    Family(Category.NATURAL_BLOCKS, "DYE", 0),
    Family(Category.NATURAL_BLOCKS, "HARNESS", 0),
    Family(Category.NATURAL_BLOCKS, "WALL_BANNER", 0),
    Family(Category.NATURAL_BLOCKS, "CRACKED_POLISHED_BLACKSTONE", 0),
    Family(Category.NATURAL_BLOCKS, "CRACKED_POLISHED_BLACKSTONE_BRICKS", 0),
    Family(Category.NATURAL_BLOCKS, "REDSTONE_WIRE", 0),
    # Nether
    Family(Category.NATURAL_BLOCKS, "NETHER", 0),
    Family(Category.NATURAL_BLOCKS, "NETHER_PORTAL", 0),
    Family(Category.NATURAL_BLOCKS, "SMOOTH_QUARTZ", 0),
    Family(Category.NATURAL_BLOCKS, "SOUL", 0),
    # End
    Family(Category.NATURAL_BLOCKS, "CHORUS", 0),
    # Special & Decorative
    Family(Category.NATURAL_BLOCKS, "ANVIL", 0),
    Family(Category.NATURAL_BLOCKS, "BARREL", 0),
    Family(Category.NATURAL_BLOCKS, "BEE", 0),
    Family(Category.NATURAL_BLOCKS, "CAMPFIRE", 0),
    Family(Category.NATURAL_BLOCKS, "FLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "INFESTED", 0),
    Family(Category.NATURAL_BLOCKS, "LIGHT", 0),
    Family(Category.NATURAL_BLOCKS, "NOTE", 0),
    # Froglight
    Family(Category.NATURAL_BLOCKS, "PILLAR", 0),
    Family(Category.NATURAL_BLOCKS, "RESPAWN_ANCHOR", 0),
    Family(Category.NATURAL_BLOCKS, "TRIAL", 0),
    Family(Category.NATURAL_BLOCKS, "TRIAL_SPAWNER", 0),
    Family(Category.NATURAL_BLOCKS, "WAXED_EXPOSED_LIGHTNING_ROD", 0),
    Family(Category.NATURAL_BLOCKS, "WAXED_OXIDIZED_LIGHTNING_ROD", 0),
    Family(Category.NATURAL_BLOCKS, "WAXED_WEATHERED_LIGHTNING_ROD", 0),
    Family(Category.NATURAL_BLOCKS, "WITHER_ROSE", 0),
    Family(Category.NATURAL_BLOCKS, "WOLF_ARMOR", 0),
    # Natural Blocks
    # Soils & Terrain
    Family(Category.NATURAL_BLOCKS, "TALL_SEAGRASS", 0),
    # Ores & Resources
    Family(Category.NATURAL_BLOCKS, "COAL", 0),
    Family(Category.NATURAL_BLOCKS, "NETHER_QUARTZ", 0),
    # Trees & Foliage
    Family(Category.NATURAL_BLOCKS, "MANGROVE_PROPAGULE", 0),
    Family(Category.NATURAL_BLOCKS, "WARPED_ROOTS", 0),
    # Flowers & Plants
    Family(Category.NATURAL_BLOCKS, "DANDELION", 0),
    Family(Category.NATURAL_BLOCKS, "POPPY", 0),
    Family(Category.NATURAL_BLOCKS, "BLUE_ORCHID", 0),
    Family(Category.NATURAL_BLOCKS, "ALLIUM", 0),
    Family(Category.NATURAL_BLOCKS, "AZURE_BLUET", 0),
    Family(Category.NATURAL_BLOCKS, "RED_TULIP", 0),
    Family(Category.NATURAL_BLOCKS, "ORANGE_TULIP", 0),
    Family(Category.NATURAL_BLOCKS, "WHITE_TULIP", 0),
    Family(Category.NATURAL_BLOCKS, "PINK_TULIP", 0),
    Family(Category.NATURAL_BLOCKS, "OXEYE_DAISY", 0),
    Family(Category.NATURAL_BLOCKS, "CORNFLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "LILY_OF_THE_VALLEY", 0),
    Family(Category.NATURAL_BLOCKS, "TORCHFLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "CACTUS_FLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "CLOSED_EYEBLOSSOM", 0),
    Family(Category.NATURAL_BLOCKS, "OPEN_EYEBLOSSOM", 0),
    Family(Category.NATURAL_BLOCKS, "PINK_PETALS", 0),
    Family(Category.NATURAL_BLOCKS, "WILDFLOWERS", 0),
    Family(Category.NATURAL_BLOCKS, "LEAF_LITTER", 0),
    Family(Category.NATURAL_BLOCKS, "SPORE_BLOSSOM", 0),
    Family(Category.NATURAL_BLOCKS, "FIREFLY_BUSH", 0),
    Family(Category.NATURAL_BLOCKS, "SWEET_BERRY_BUSH", 0),
    # Ocean & Coral
    Family(Category.NATURAL_BLOCKS, "CORAL", 0),
    Family(Category.NATURAL_BLOCKS, "TUBE_CORAL", 0),
    # Ice & Snow
    Family(Category.NATURAL_BLOCKS, "SNOWBALL", 0),
    # Sculk
    # Special Natural
    Family(Category.NATURAL_BLOCKS, "CAVE", 0),
    Family(Category.NATURAL_BLOCKS, "COCOA", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_CHEST", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_LANTERN", 0),
    Family(Category.NATURAL_BLOCKS, "DRIED_GHAST", 0),
    Family(Category.NATURAL_BLOCKS, "EXPOSED_CHISELED_COPPER", 0),
    Family(Category.NATURAL_BLOCKS, "EXPOSED_CUT_COPPER", 0),
    Family(Category.NATURAL_BLOCKS, "INFESTED_CHISELED_STONE_BRICKS", 0),
    Family(Category.NATURAL_BLOCKS, "INFESTED_COBBLESTONE", 0),
    Family(Category.NATURAL_BLOCKS, "INFESTED_CRACKED_STONE_BRICKS", 0),
    Family(Category.NATURAL_BLOCKS, "POTATO", 0),
    Family(Category.NATURAL_BLOCKS, "VINE", 0),
    Family(Category.NATURAL_BLOCKS, "WITHER_ROSE", 0),
    # Functional Blocks
    # Copper
    Family(Category.FUNCTIONAL_BLOCKS, "OXIDIZED_CHISELED_COPPER", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "OXIDIZED_CUT_COPPER", 0),
    # Utility & Decoration
    Family(Category.FUNCTIONAL_BLOCKS, "ARMOR_STAND", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "BEACON", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "CHIPPED_ANVIL", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "DECORATED_POT", 0),
    # Special Functional
    Family(Category.FUNCTIONAL_BLOCKS, "PETRIFIED_OAK_SLAB", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "PITCHER_CROP", 0),
    # Redstone Blocks
    # Redstone Power
    Family(Category.REDSTONE_BLOCKS, "REDSTONE_BLOCK", 0),
    # Redstone Machines
    Family(Category.REDSTONE_BLOCKS, "CREAKING_HEART", 0),
    # Redstone Controls & Transport
    Family(Category.REDSTONE_BLOCKS, "TRIPWIRE", 0),
    # Redstone Misc
    Family(Category.REDSTONE_BLOCKS, "CRAFTING_TABLE", 0),
    Family(Category.REDSTONE_BLOCKS, "TNT", 0),
    # Tools And Utilities
    # Tools
    Family(Category.TOOLS_AND_UTILITIES, "AXE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AXE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HOE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PICKAXE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHOVEL", 0),
    # Rails
    Family(Category.TOOLS_AND_UTILITIES, "ACTIVATOR", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ALLAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AMETHYST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AMETHYST_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "APPLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMADILLO", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMADILLO_SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMOR_STAND", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "ARMOR_TRIM", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ARROW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AXOLOTL", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "AXOLOTL_BUCKET", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BARRIER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BAT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BEE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLADE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_POWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BOGGED", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BONE_MEAL", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "BOOK", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BOW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BRICK", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "BRUSH", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BUBBLE_COLUMN", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BUNDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAMEL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CARROT_ON_A_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAVE_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAVE_SPIDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHAINMAIL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHAIN_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHARCOAL", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "CHEST_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "CHICKEN", 0),
    # Books & Maps
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "CHISELED_QUARTZ", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CINNABAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLAY_BALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COAL", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "COD", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "COD_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "COMMAND_BLOCK", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "COMMAND_BLOCK_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER_NUGGET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CREAKING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CREEPER", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "CREEPER_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CROSSBOW", 0),
    # Technical
    Family(Category.TOOLS_AND_UTILITIES, "DEBUG_STICK", 0),
    # Music
    Family(Category.TOOLS_AND_UTILITIES, "DISC_FRAGMENT", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "DOLPHIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DONKEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON_BREATH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DROWNED", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ECHO_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EGG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ELDER_GUARDIAN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ELYTRA", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "ENCHANTED_BOOK", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ENCHANTED_GOLDEN_APPLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDERMAN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_DRAGON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_PEARL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_CRYSTAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_GATEWAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_PORTAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EVOKER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EXPERIENCE_BOTTLE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FERMENTED_SPIDER_EYE", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "FILLED_MAP", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FIRE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_ROCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIRE_CHARGE", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "FISHING_ROD", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FLINT", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "FLINT_AND_STEEL", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FOX", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FROG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FROSTED_ICE", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "FURNACE_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "GHAST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GHAST_TEAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLASS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLISTERING_MELON_SLICE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOWSTONE_DUST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOWSTONE_DUST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_SQUID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOAT", 0),
    # Music
    Family(Category.TOOLS_AND_UTILITIES, "GOAT_HORN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "GOLD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLDEN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLDEN_APPLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLDEN_CARROT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLD_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLD_NUGGET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GUARDIAN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GUNPOWDER", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "HEART_OF_THE_SEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HEAVY_CORE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HOGLIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HONEYCOMB", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HONEY_BOTTLE", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "HOPPER_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "HORSE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "HUSK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON_GOLEM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON_NUGGET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "JIGSAW", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "KNOWLEDGE_BOOK", 0),
    # Utility Tools
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "LAPIS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAPIS_LAZULI", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAVA", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "LAVA_BUCKET", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "LEAD", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "LEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LINGERING_POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LLAMA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MACE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAGMA_CREAM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAGMA_CUBE", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "MAP", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "MILK_BUCKET", 0),
    # Minecarts
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "MOOSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MOVING_PISTON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MULE", 0),
    # Music
    Family(Category.TOOLS_AND_UTILITIES, "MUSIC_DISC", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "NAME_TAG", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE_SCRAP", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "NETHER_BRICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHER_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OCELOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_TRIAL_KEY", 0),
    # Decoration
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "PANDA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PARCHED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PARROT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PHANTOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PHANTOM_MEMBRANE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN_BRUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PILLAGER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PISTON_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PLAYER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PLAYER_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POLAR_BEAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTATOES", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ACACIA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ACACIA_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ALLIUM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_AZALEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_AZURE_BLUET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BAMBOO", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BIRCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BIRCH_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BLUE_ORCHID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BROWN_MUSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CACTUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CHERRY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CHERRY_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CLOSED_EYEBLOSSOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CORNFLOWER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON_FUNGUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON_ROOTS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DANDELION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DARK_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DARK_OAK_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DEAD_BUSH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_FERN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_FLOWERING_AZALEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_GOLDEN_DANDELION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_JUNGLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_JUNGLE_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_LILY_OF_THE_VALLEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_MANGROVE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_MANGROVE_PROPAGULE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OAK_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OPEN_EYEBLOSSOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ORANGE_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OXEYE_DAISY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PALE_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PALE_OAK_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PINK_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_POPPY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_RED_MUSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_RED_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_SPRUCE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_SPRUCE_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_TORCHFLOWER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED_FUNGUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED_ROOTS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WHITE_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WITHER_ROSE", 0),
    # Pottery
    Family(Category.TOOLS_AND_UTILITIES, "POTTERY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTERY_SHERD", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "POWDER_SNOW", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "POWDER_SNOW_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "PRISMARINE_CRYSTALS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PRISMARINE_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PUFFERFISH", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "PUFFERFISH_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "QUARTZ", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_FOOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_HIDE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "RAVAGER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RECOVERY_COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REDSTONE_WALL_TORCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REPEATING_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RESIN_CLUMP", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ROTTEN_FLESH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SADDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SALMON", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "SALMON_BUCKET", 0),
    # Utility Tools
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SCUTE", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "SHEARS", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SHEEP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHIELD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHULKER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHULKER_SHELL", 0),
    # Patterns & Templates
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SILVERFISH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SKELETON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SKELETON_SKULL", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SLIME_BALL", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "SMITHING_TEMPLATE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SNIFFER", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SNOWBALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SNOW_GOLEM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SOUL_FIRE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SOUL_WALL_TORCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPAWNER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPECTRAL_ARROW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPIDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPIDER_EYE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SPLASH_POTION", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "SPYGLASS", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SQUID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRIDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRING", 0),
    # Technical
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_VOID", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SUGAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SULFUR_CUBE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TADPOLE", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "TADPOLE_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TEST_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TEST_INSTANCE_BLOCK", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TIPPED_ARROW", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "TNT_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TOTEM", 0),
    # Special
    Family(Category.TOOLS_AND_UTILITIES, "TOTEM_OF_UNDYING", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TRADER_LLAMA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TRIAL_KEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TRIDENT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TROPICAL_FISH", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "TROPICAL_FISH_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE_SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VEX", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "VILLAGER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VINDICATOR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VOID_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WALL_HANGING_SIGN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WALL_SIGN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WALL_TORCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WANDERING_TRADER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WARDEN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "WARPED_FUNGUS_ON_A_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WATER", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "WATER_BUCKET", 0),
    # Special
    Family(Category.TOOLS_AND_UTILITIES, "WIND_CHARGE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "WITCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WITHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WITHER_SKELETON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WITHER_SKELETON_SKULL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WOLF", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "WRITABLE_BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WRITTEN_BOOK", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ZOGLIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ZOMBIE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ZOMBIE_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ZOMBIFIED_PIGLIN", 0),
    # Combat
    # Melee Weapons
    Family(Category.COMBAT, "MACE", 0),
    Family(Category.COMBAT, "SPEAR", 0),
    Family(Category.COMBAT, "SWORD", 0),
    Family(Category.COMBAT, "TRIDENT", 0),
    # Ranged Weapons
    Family(Category.COMBAT, "ARROW", 0),
    Family(Category.COMBAT, "BOW", 0),
    Family(Category.COMBAT, "CROSSBOW", 0),
    Family(Category.COMBAT, "SPECTRAL_ARROW", 0),
    Family(Category.COMBAT, "TIPPED_ARROW", 0),
    # Armor & Protection
    Family(Category.COMBAT, "CHAINMAIL", 0),
    Family(Category.COMBAT, "COPPER", 0),
    Family(Category.COMBAT, "DIAMOND", 0),
    Family(Category.COMBAT, "GOLDEN", 0),
    Family(Category.COMBAT, "HORSE", 0),
    Family(Category.COMBAT, "HORSE_ARMOR", 0),
    Family(Category.COMBAT, "IRON", 0),
    Family(Category.COMBAT, "LEATHER", 0),
    Family(Category.COMBAT, "NAUTILUS", 0),
    Family(Category.COMBAT, "NAUTILUS_ARMOR", 0),
    Family(Category.COMBAT, "NETHERITE", 0),
    Family(Category.COMBAT, "STONE", 0),
    Family(Category.COMBAT, "TURTLE", 0),
    Family(Category.COMBAT, "WOLF", 0),
    Family(Category.COMBAT, "WOODEN", 0),
    # Special Combat
    Family(Category.COMBAT, "ELYTRA", 0),
    Family(Category.COMBAT, "SHIELD", 0),
    Family(Category.COMBAT, "TOTEM_OF_UNDYING", 0),
    # Food And Drinks
    # Meat & Fish
    Family(Category.FOOD_AND_DRINKS, "BEEF", 0),
    Family(Category.FOOD_AND_DRINKS, "CHICKEN", 0),
    Family(Category.FOOD_AND_DRINKS, "COD", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_BEEF", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_CHICKEN", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_COD", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_MUTTON", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_PORKCHOP", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_RABBIT", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_SALMON", 0),
    Family(Category.FOOD_AND_DRINKS, "MUTTON", 0),
    Family(Category.FOOD_AND_DRINKS, "PORKCHOP", 0),
    Family(Category.FOOD_AND_DRINKS, "RABBIT", 0),
    Family(Category.FOOD_AND_DRINKS, "SALMON", 0),
    Family(Category.FOOD_AND_DRINKS, "TROPICAL_FISH", 0),
    # Plants & Prepared Foods
    Family(Category.FOOD_AND_DRINKS, "BAKED_POTATO", 0),
    Family(Category.FOOD_AND_DRINKS, "BEETROOT", 0),
    Family(Category.FOOD_AND_DRINKS, "BEETROOTS", 0),
    Family(Category.FOOD_AND_DRINKS, "BEETROOT_SOUP", 0),
    Family(Category.FOOD_AND_DRINKS, "BREAD", 0),
    Family(Category.FOOD_AND_DRINKS, "CAKE", 0),
    Family(Category.FOOD_AND_DRINKS, "CARROT", 0),
    Family(Category.FOOD_AND_DRINKS, "CARROTS", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKIE", 0),
    Family(Category.FOOD_AND_DRINKS, "GOLDEN_CARROT", 0),
    Family(Category.FOOD_AND_DRINKS, "MELON_SLICE", 0),
    Family(Category.FOOD_AND_DRINKS, "MELON_STEM", 0),
    Family(Category.FOOD_AND_DRINKS, "MUSHROOM_STEW", 0),
    Family(Category.FOOD_AND_DRINKS, "POISONOUS_POTATO", 0),
    Family(Category.FOOD_AND_DRINKS, "POTATO", 0),
    Family(Category.FOOD_AND_DRINKS, "PUMPKIN_PIE", 0),
    Family(Category.FOOD_AND_DRINKS, "PUMPKIN_STEM", 0),
    Family(Category.FOOD_AND_DRINKS, "RABBIT_STEW", 0),
    Family(Category.FOOD_AND_DRINKS, "SUSPICIOUS_STEW", 0),
    # Special Foods
    Family(Category.FOOD_AND_DRINKS, "APPLE", 0),
    Family(Category.FOOD_AND_DRINKS, "CHORUS_FRUIT", 0),
    Family(Category.FOOD_AND_DRINKS, "EGG", 0),
    Family(Category.FOOD_AND_DRINKS, "GOLDEN_APPLE", 0),
    Family(Category.FOOD_AND_DRINKS, "HONEY_BOTTLE", 0),
    Family(Category.FOOD_AND_DRINKS, "MILK_BUCKET", 0),
    Family(Category.FOOD_AND_DRINKS, "POPPED_CHORUS_FRUIT", 0),
    # Ingredients
    # Minerals & Metals
    Family(Category.INGREDIENTS, "AMETHYST_SHARD", 0),
    Family(Category.INGREDIENTS, "ANCIENT_DEBRIS", 0),
    Family(Category.INGREDIENTS, "CHARCOAL", 0),
    Family(Category.INGREDIENTS, "COAL", 0),
    Family(Category.INGREDIENTS, "COPPER_INGOT", 0),
    Family(Category.INGREDIENTS, "COPPER_NUGGET", 0),
    Family(Category.INGREDIENTS, "DIAMOND", 0),
    Family(Category.INGREDIENTS, "EMERALD", 0),
    Family(Category.INGREDIENTS, "GOLD_INGOT", 0),
    Family(Category.INGREDIENTS, "GOLD_NUGGET", 0),
    Family(Category.INGREDIENTS, "IRON_INGOT", 0),
    Family(Category.INGREDIENTS, "IRON_NUGGET", 0),
    Family(Category.INGREDIENTS, "LAPIS_LAZULI", 0),
    Family(Category.INGREDIENTS, "NETHERITE_INGOT", 0),
    Family(Category.INGREDIENTS, "NETHERITE_SCRAP", 0),
    Family(Category.INGREDIENTS, "QUARTZ", 0),
    Family(Category.INGREDIENTS, "REDSTONE", 0),
    # Mob & Crafting Ingredients
    Family(Category.INGREDIENTS, "BLAZE_POWDER", 0),
    Family(Category.INGREDIENTS, "BLAZE_ROD", 0),
    Family(Category.INGREDIENTS, "BONE", 0),
    Family(Category.INGREDIENTS, "BONE_MEAL", 0),
    Family(Category.INGREDIENTS, "BREEZE_ROD", 0),
    Family(Category.INGREDIENTS, "BRICK", 0),
    Family(Category.INGREDIENTS, "CLAY_BALL", 0),
    Family(Category.INGREDIENTS, "FEATHER", 0),
    Family(Category.INGREDIENTS, "GHAST_TEAR", 0),
    Family(Category.INGREDIENTS, "GLOW_INK_SAC", 0),
    Family(Category.INGREDIENTS, "GUNPOWDER", 0),
    Family(Category.INGREDIENTS, "INK_SAC", 0),
    Family(Category.INGREDIENTS, "LEATHER", 0),
    Family(Category.INGREDIENTS, "MAGMA_CREAM", 0),
    Family(Category.INGREDIENTS, "NAUTILUS_SHELL", 0),
    Family(Category.INGREDIENTS, "NETHER_STAR", 0),
    Family(Category.INGREDIENTS, "PHANTOM_MEMBRANE", 0),
    Family(Category.INGREDIENTS, "RABBIT_HIDE", 0),
    Family(Category.INGREDIENTS, "ROTTEN_FLESH", 0),
    Family(Category.INGREDIENTS, "SHULKER_SHELL", 0),
    Family(Category.INGREDIENTS, "SLIME_BALL", 0),
    Family(Category.INGREDIENTS, "SPIDER_EYE", 0),
    Family(Category.INGREDIENTS, "STICK", 0),
    Family(Category.INGREDIENTS, "STRING", 0),
    Family(Category.INGREDIENTS, "SUGAR", 0),
    Family(Category.INGREDIENTS, "WHEAT", 0),
    # Books & Paper
    Family(Category.INGREDIENTS, "BOOK", 0),
    Family(Category.INGREDIENTS, "ENCHANTED_BOOK", 0),
    Family(Category.INGREDIENTS, "PAPER", 0),
    Family(Category.INGREDIENTS, "WRITABLE_BOOK", 0),
    Family(Category.INGREDIENTS, "WRITTEN_BOOK", 0),
    # Templates & Patterns
    Family(Category.INGREDIENTS, "BANNER_PATTERN", 0),
    Family(Category.INGREDIENTS, "SMITHING", 0),
    Family(Category.INGREDIENTS, "SMITHING_TEMPLATE", 0),
    # Pottery
    Family(Category.INGREDIENTS, "POTTERY", 0),
    Family(Category.INGREDIENTS, "POTTERY_SHERD", 0),
    # Brewing & Miscellaneous
    Family(Category.INGREDIENTS, "APPLE", 0),
    Family(Category.INGREDIENTS, "ARMADILLO_SCUTE", 0),
    Family(Category.INGREDIENTS, "BEETROOT", 0),
    Family(Category.INGREDIENTS, "BOWL", 0),
    Family(Category.INGREDIENTS, "BROWN_MUSHROOM", 0),
    Family(Category.INGREDIENTS, "BUNDLE", 0),
    Family(Category.INGREDIENTS, "CARROT", 0),
    Family(Category.INGREDIENTS, "CHORUS_FRUIT", 0),
    Family(Category.INGREDIENTS, "CINNABAR", 0),
    Family(Category.INGREDIENTS, "DRAGON_BREATH", 0),
    Family(Category.INGREDIENTS, "DRIED_KELP", 0),
    Family(Category.INGREDIENTS, "ECHO_SHARD", 0),
    Family(Category.INGREDIENTS, "EGG", 0),
    Family(Category.INGREDIENTS, "ENDER_EYE", 0),
    Family(Category.INGREDIENTS, "ENDER_PEARL", 0),
    Family(Category.INGREDIENTS, "END_ROD", 0),
    Family(Category.INGREDIENTS, "FERMENTED_SPIDER_EYE", 0),
    Family(Category.INGREDIENTS, "FIREWORK_STAR", 0),
    Family(Category.INGREDIENTS, "FLINT", 0),
    Family(Category.INGREDIENTS, "GLASS_BOTTLE", 0),
    Family(Category.INGREDIENTS, "GLISTERING_MELON_SLICE", 0),
    Family(Category.INGREDIENTS, "GLOWSTONE_DUST", 0),
    Family(Category.INGREDIENTS, "GLOW_BERRIES", 0),
    Family(Category.INGREDIENTS, "GOLDEN_DANDELION", 0),
    Family(Category.INGREDIENTS, "HEART_OF_THE_SEA", 0),
    Family(Category.INGREDIENTS, "HEAVY_CORE", 0),
    Family(Category.INGREDIENTS, "HONEYCOMB", 0),
    Family(Category.INGREDIENTS, "HONEY_BOTTLE", 0),
    Family(Category.INGREDIENTS, "KELP", 0),
    Family(Category.INGREDIENTS, "MELON", 0),
    Family(Category.INGREDIENTS, "MUSHROOM", 0),
    Family(Category.INGREDIENTS, "NETHER_BRICK", 0),
    Family(Category.INGREDIENTS, "OMINOUS_TRIAL_KEY", 0),
    Family(Category.INGREDIENTS, "POPPED_CHORUS_FRUIT", 0),
    Family(Category.INGREDIENTS, "POTATO", 0),
    Family(Category.INGREDIENTS, "PRISMARINE_CRYSTALS", 0),
    Family(Category.INGREDIENTS, "PRISMARINE_SHARD", 0),
    Family(Category.INGREDIENTS, "PUMPKIN", 0),
    Family(Category.INGREDIENTS, "RABBIT_FOOT", 0),
    Family(Category.INGREDIENTS, "RAW_COPPER", 0),
    Family(Category.INGREDIENTS, "RAW_GOLD", 0),
    Family(Category.INGREDIENTS, "RAW_IRON", 0),
    Family(Category.INGREDIENTS, "RED_MUSHROOM", 0),
    Family(Category.INGREDIENTS, "RESIN_CLUMP", 0),
    Family(Category.INGREDIENTS, "SEEDS", 0),
    Family(Category.INGREDIENTS, "SNOWBALL", 0),
    Family(Category.INGREDIENTS, "SULFUR_CUBE_BUCKET", 0),
    Family(Category.INGREDIENTS, "SWEET_BERRIES", 0),
    Family(Category.INGREDIENTS, "TRIAL_KEY", 0),
    Family(Category.INGREDIENTS, "TURTLE_SCUTE", 0),
    Family(Category.INGREDIENTS, "WIND_CHARGE", 0),
    # Spawn Eggs
    # Passive & Neutral
    Family(Category.SPAWN_EGGS, "ALLAY", 0),
    Family(Category.SPAWN_EGGS, "ARMADILLO", 0),
    Family(Category.SPAWN_EGGS, "BAT", 0),
    Family(Category.SPAWN_EGGS, "BEE", 0),
    Family(Category.SPAWN_EGGS, "CAMEL", 0),
    Family(Category.SPAWN_EGGS, "CAT", 0),
    Family(Category.SPAWN_EGGS, "CHICKEN", 0),
    Family(Category.SPAWN_EGGS, "COW", 0),
    Family(Category.SPAWN_EGGS, "DONKEY", 0),
    Family(Category.SPAWN_EGGS, "FOX", 0),
    Family(Category.SPAWN_EGGS, "FROG", 0),
    Family(Category.SPAWN_EGGS, "GOAT", 0),
    Family(Category.SPAWN_EGGS, "HAPPY_GHAST", 0),
    Family(Category.SPAWN_EGGS, "HORSE", 0),
    Family(Category.SPAWN_EGGS, "IRON_GOLEM", 0),
    Family(Category.SPAWN_EGGS, "LLAMA", 0),
    Family(Category.SPAWN_EGGS, "MOOSHROOM", 0),
    Family(Category.SPAWN_EGGS, "MULE", 0),
    Family(Category.SPAWN_EGGS, "OCELOT", 0),
    Family(Category.SPAWN_EGGS, "PANDA", 0),
    Family(Category.SPAWN_EGGS, "PARROT", 0),
    Family(Category.SPAWN_EGGS, "SHEEP", 0),
    Family(Category.SPAWN_EGGS, "SNIFFER", 0),
    Family(Category.SPAWN_EGGS, "SNOW_GOLEM", 0),
    Family(Category.SPAWN_EGGS, "TRADER_LLAMA", 0),
    Family(Category.SPAWN_EGGS, "VILLAGER", 0),
    Family(Category.SPAWN_EGGS, "WANDERING_TRADER", 0),
    Family(Category.SPAWN_EGGS, "WOLF", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE_HORSE", 0),
    # Aquatic
    Family(Category.SPAWN_EGGS, "AXOLOTL", 0),
    Family(Category.SPAWN_EGGS, "COD", 0),
    Family(Category.SPAWN_EGGS, "DOLPHIN", 0),
    Family(Category.SPAWN_EGGS, "GLOW_SQUID", 0),
    Family(Category.SPAWN_EGGS, "GUARDIAN", 0),
    Family(Category.SPAWN_EGGS, "NAUTILUS", 0),
    Family(Category.SPAWN_EGGS, "PUFFERFISH", 0),
    Family(Category.SPAWN_EGGS, "SALMON", 0),
    Family(Category.SPAWN_EGGS, "SQUID", 0),
    Family(Category.SPAWN_EGGS, "TADPOLE", 0),
    Family(Category.SPAWN_EGGS, "TROPICAL_FISH", 0),
    Family(Category.SPAWN_EGGS, "TURTLE", 0),
    # Nether Mobs
    Family(Category.SPAWN_EGGS, "BLAZE", 0),
    Family(Category.SPAWN_EGGS, "GHAST", 0),
    Family(Category.SPAWN_EGGS, "HOGLIN", 0),
    Family(Category.SPAWN_EGGS, "MAGMA_CUBE", 0),
    Family(Category.SPAWN_EGGS, "PIGLIN", 0),
    Family(Category.SPAWN_EGGS, "PIGLIN_BRUTE", 0),
    Family(Category.SPAWN_EGGS, "STRIDER", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIFIED_PIGLIN", 0),
    # Undead
    Family(Category.SPAWN_EGGS, "DROWNED", 0),
    Family(Category.SPAWN_EGGS, "HUSK", 0),
    Family(Category.SPAWN_EGGS, "SKELETON", 0),
    Family(Category.SPAWN_EGGS, "SKELETON_HORSE", 0),
    Family(Category.SPAWN_EGGS, "STRAY", 0),
    Family(Category.SPAWN_EGGS, "WITHER", 0),
    Family(Category.SPAWN_EGGS, "WITHER_SKELETON", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE_VILLAGER", 0),
    # Hostile & Other
    Family(Category.SPAWN_EGGS, "BOGGED", 0),
    Family(Category.SPAWN_EGGS, "BREEZE", 0),
    Family(Category.SPAWN_EGGS, "CAMEL_HUSK", 0),
    Family(Category.SPAWN_EGGS, "CAVE_SPIDER", 0),
    Family(Category.SPAWN_EGGS, "COPPER_GOLEM", 0),
    Family(Category.SPAWN_EGGS, "CREAKING", 0),
    Family(Category.SPAWN_EGGS, "CREEPER", 0),
    Family(Category.SPAWN_EGGS, "ELDER_GUARDIAN", 0),
    Family(Category.SPAWN_EGGS, "ENDERMAN", 0),
    Family(Category.SPAWN_EGGS, "ENDERMITE", 0),
    Family(Category.SPAWN_EGGS, "ENDER_DRAGON", 0),
    Family(Category.SPAWN_EGGS, "EVOKER", 0),
    Family(Category.SPAWN_EGGS, "PARCHED", 0),
    Family(Category.SPAWN_EGGS, "PHANTOM", 0),
    Family(Category.SPAWN_EGGS, "PIG", 0),
    Family(Category.SPAWN_EGGS, "PILLAGER", 0),
    Family(Category.SPAWN_EGGS, "POLAR_BEAR", 0),
    Family(Category.SPAWN_EGGS, "RABBIT", 0),
    Family(Category.SPAWN_EGGS, "RAVAGER", 0),
    Family(Category.SPAWN_EGGS, "SHULKER", 0),
    Family(Category.SPAWN_EGGS, "SILVERFISH", 0),
    Family(Category.SPAWN_EGGS, "SPIDER", 0),
    Family(Category.SPAWN_EGGS, "VEX", 0),
    Family(Category.SPAWN_EGGS, "VINDICATOR", 0),
    Family(Category.SPAWN_EGGS, "WARDEN", 0),
    Family(Category.SPAWN_EGGS, "WITCH", 0),
    Family(Category.SPAWN_EGGS, "ZOGLIN", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE_NAUTILUS", 0),
    # Miscellaneous
    Family(Category.OTHER, "CORAL_WALL_FAN", 0),
]

VARIANTS: list[Variant] = [
    # The `order`s here reset to 0 for each exclusive variant to
    # a specific group of variants. For example, `LOG` and `STEM` cannot
    # belong to the same family, so there is no need to decide whether one
    # has a higher priority than the other.
    #
    # Wood
    Variant("LOG", Affix.SUFFIX, 0),
    Variant("STEM", Affix.SUFFIX, 0),  # Nether variant for LOG
    Variant("WOOD", Affix.SUFFIX, 1),
    Variant("HYPHAE", Affix.SUFFIX, 1),  # Nether variant for WOOD
    Variant("STRIPPED", Affix.PREFIX, 2),
    Variant("PLANKS", Affix.SUFFIX, 3),
    # General
    Variant("STAIRS", Affix.SUFFIX, 4),
    Variant("SLAB", Affix.SUFFIX, 5),
    Variant("WALL", Affix.SUFFIX, 6),
    Variant("FENCE", Affix.SUFFIX, 7),
    Variant("FENCE_GATE", Affix.SUFFIX, 8),
    Variant("DOOR", Affix.SUFFIX, 9),
    Variant("TRAPDOOR", Affix.SUFFIX, 10),
    Variant("PRESSURE_PLATE", Affix.SUFFIX, 11),
    Variant("BUTTON", Affix.SUFFIX, 12),
    Variant("BOAT", Affix.SUFFIX, 13),
    Variant("RAFT", Affix.SUFFIX, 13),  # Bamboo variant for BOAT
    Variant("CHEST_BOAT", Affix.SUFFIX, 14),
    Variant("CHEST_RAFT", Affix.SUFFIX, 14),  # Bamboo variant for CHEST_BOAT
    Variant("SIGN", Affix.SUFFIX, 15),
    Variant("HANGING_SIGN", Affix.SUFFIX, 16),
    # Variant("LEAVES", Affix.SUFFIX, 17),
    # Variant("SAPLING", Affix.SUFFIX, 18),
    # Variant("PROPAGULE", Affix.SUFFIX, 18),  # Mangrove variant for SAPLING
    Variant("SHELF", Affix.SUFFIX, 19),
    Variant("WALL_HANGING_SIGN", Affix.SUFFIX, 20),
    Variant("WALL_SIGN", Affix.SUFFIX, 21),
    # Deepslate
    Variant("CRACKED", Affix.PREFIX, 0),
    Variant("CHISELED", Affix.PREFIX, 1),
    # Copper
    Variant("EXPOSED", Affix.PREFIX, 0),
    Variant("WEATHERED", Affix.PREFIX, 1),
    Variant("OXIDIZED", Affix.PREFIX, 2),
    Variant("EXPOSED_CHISELED", Affix.PREFIX, 0),
    Variant("WEATHERED_CHISELED", Affix.PREFIX, 1),
    Variant("OXIDIZED_CHISELED", Affix.PREFIX, 2),
    # ---
    Variant("WAXED", Affix.PREFIX, 3),
    Variant("MOSAIC", Affix.SUFFIX, 0),
    Variant("SPAWN_EGG", Affix.SUFFIX, 0),
    Variant("BLOCK", Affix.SUFFIX, 0),
    Variant("POTTERY_SHERD", Affix.SUFFIX, 0),
    Variant("CHEST", Affix.SUFFIX, 0),
    Variant("BARS", Affix.SUFFIX, 0),
    Variant("BULB", Affix.SUFFIX, 0),
    Variant("CHAIN", Affix.SUFFIX, 0),
    Variant("GRATE", Affix.SUFFIX, 0),
    Variant("LANTERN", Affix.SUFFIX, 0),
    Variant("WALL_TORCH", Affix.SUFFIX, 0),
    Variant("LIGHTNING_ROD", Affix.SUFFIX, 0),
    Variant("WALL_BANNER", Affix.SUFFIX, 0),
    Variant("CANDLE_CAKE", Affix.SUFFIX, 0),
    Variant("HARNESS", Affix.SUFFIX, 0),
    Variant("ORE", Affix.SUFFIX, 0),
    Variant("FAN", Affix.SUFFIX, 0),
    Variant("WALL_FAN", Affix.SUFFIX, 0),
    Variant("MUSHROOM_BLOCK", Affix.SUFFIX, 0),
    Variant("VINES", Affix.SUFFIX, 0),
    Variant("VINES_PLANT", Affix.SUFFIX, 0),
    Variant("FUNGUS", Affix.SUFFIX, 0),
    Variant("NYLIUM", Affix.SUFFIX, 0),
    Variant("ROOTS", Affix.SUFFIX, 0),
    Variant("WART_BLOCK", Affix.SUFFIX, 0),
    Variant("CAULDRON", Affix.SUFFIX, 0),
    Variant("PILLAR", Affix.SUFFIX, 0),
    Variant("ORE", Affix.SUFFIX, 0),
    Variant("PLANT", Affix.SUFFIX, 0),
    Variant("CROP", Affix.SUFFIX, 0),
    Variant("SEEDS", Affix.SUFFIX, 0),
    Variant("BUSH", Affix.SUFFIX, 0),
    # Rails
    Variant("ACTIVATOR", Affix.PREFIX, 0),
    Variant("DETECTOR", Affix.PREFIX, 0),
    Variant("POWERED", Affix.PREFIX, 0),
    # Amethyst
    Variant("BUDDING", Affix.PREFIX, 0),
    Variant("CLUSTER", Affix.SUFFIX, 0),
    # Colored
    Variant("WHITE", Affix.PREFIX, 0),
    Variant("LIGHT_GRAY", Affix.PREFIX, 1),
    Variant("GRAY", Affix.PREFIX, 2),
    Variant("BLACK", Affix.PREFIX, 3),
    Variant("BROWN", Affix.PREFIX, 4),
    Variant("RED", Affix.PREFIX, 5),
    Variant("ORANGE", Affix.PREFIX, 6),
    Variant("YELLOW", Affix.PREFIX, 7),
    Variant("LIME", Affix.PREFIX, 8),
    Variant("GREEN", Affix.PREFIX, 9),
    Variant("CYAN", Affix.PREFIX, 10),
    Variant("LIGHT_BLUE", Affix.PREFIX, 11),
    Variant("BLUE", Affix.PREFIX, 12),
    Variant("PURPLE", Affix.PREFIX, 13),
    Variant("MAGENTA", Affix.PREFIX, 14),
    Variant("PINK", Affix.PREFIX, 15),
    # Pottery
    Variant("ANGLER", Affix.PREFIX, 0),
    Variant("ARCHER", Affix.PREFIX, 1),
    Variant("ARMS_UP", Affix.PREFIX, 2),
    Variant("BLADE", Affix.PREFIX, 3),
    Variant("BREWER", Affix.PREFIX, 4),
    Variant("BURN", Affix.PREFIX, 5),
    Variant("DANGER", Affix.PREFIX, 6),
    Variant("EXPLORER", Affix.PREFIX, 7),
    Variant("FLOW", Affix.PREFIX, 8),
    Variant("FRIEND", Affix.PREFIX, 9),
    Variant("GUSTER", Affix.PREFIX, 10),
    Variant("HEART", Affix.PREFIX, 11),
    Variant("HEARTBREAK", Affix.PREFIX, 12),
    Variant("HOWL", Affix.PREFIX, 13),
    Variant("MINER", Affix.PREFIX, 14),
    Variant("MOURNER", Affix.PREFIX, 15),
    Variant("PLENTY", Affix.PREFIX, 16),
    Variant("PRIZE", Affix.PREFIX, 17),
    Variant("SCRAPE", Affix.PREFIX, 18),
    Variant("SHEAF", Affix.PREFIX, 19),
    Variant("SHELTER", Affix.PREFIX, 20),
    Variant("SKULL", Affix.PREFIX, 21),
    Variant("SNORT", Affix.PREFIX, 22),
    # Melon
    Variant("ATTACHED", Affix.PREFIX, 0),
    # Armor
    Variant("BOOTS", Affix.SUFFIX, 0),
    Variant("CHESTPLATE", Affix.SUFFIX, 0),
    Variant("LEGGINGS", Affix.SUFFIX, 0),
    Variant("HELMET", Affix.SUFFIX, 0),
    # Tools
    Variant("LEATHER", Affix.PREFIX, 0),
    Variant("WOODEN", Affix.PREFIX, 1),
    Variant("STONE", Affix.PREFIX, 2),
    Variant("COPPER", Affix.PREFIX, 3),
    Variant("IRON", Affix.PREFIX, 4),
    Variant("GOLDEN", Affix.PREFIX, 5),
    Variant("DIAMOND", Affix.PREFIX, 6),
    Variant("NETHERITE", Affix.PREFIX, 7),
    # Heads
    Variant("WALL_SKULL", Affix.SUFFIX, 0),
    Variant("WALL_HEAD", Affix.SUFFIX, 0),
    # Anvil
    Variant("CHIPPED", Affix.PREFIX, 0),
    Variant("DAMAGED", Affix.PREFIX, 0),
    # Silk-touched Ores
    Variant("STONE", Affix.PREFIX, 0),
    Variant("DEEPSLATE", Affix.PREFIX, 1),
    Variant("NETHER", Affix.PREFIX, 2),
    # Disc
    Variant("11", Affix.SUFFIX, 0),
    Variant("13", Affix.SUFFIX, 1),
    Variant("5", Affix.SUFFIX, 2),
    Variant("BLOCKS", Affix.SUFFIX, 3),
    Variant("BOUNCE", Affix.SUFFIX, 4),
    Variant("CAT", Affix.SUFFIX, 5),
    Variant("CHIRP", Affix.SUFFIX, 6),
    Variant("CREATOR", Affix.SUFFIX, 7),
    Variant("CREATOR_MUSIC_BOX", Affix.SUFFIX, 8),
    Variant("FAR", Affix.SUFFIX, 9),
    Variant("LAVA_CHICKEN", Affix.SUFFIX, 10),
    Variant("MALL", Affix.SUFFIX, 11),
    Variant("MELLOHI", Affix.SUFFIX, 12),
    Variant("OTHERSIDE", Affix.SUFFIX, 13),
    Variant("PIGSTEP", Affix.SUFFIX, 14),
    Variant("PRECIPICE", Affix.SUFFIX, 15),
    Variant("RELIC", Affix.SUFFIX, 16),
    Variant("STAL", Affix.SUFFIX, 17),
    Variant("STRAD", Affix.SUFFIX, 18),
    Variant("TEARS", Affix.SUFFIX, 19),
    Variant("WAIT", Affix.SUFFIX, 20),
    Variant("WARD", Affix.SUFFIX, 21),
    # Banner Pattern
    Variant("BORDURE_INDENTED", Affix.PREFIX, 0),
    Variant("CREEPER", Affix.PREFIX, 1),
    Variant("FIELD_MASONED", Affix.PREFIX, 2),
    Variant("FLOW", Affix.PREFIX, 3),
    Variant("FLOWER", Affix.PREFIX, 4),
    Variant("GLOBE", Affix.PREFIX, 5),
    Variant("GUSTER", Affix.PREFIX, 6),
    Variant("MOJANG", Affix.PREFIX, 7),
    Variant("PIGLIN", Affix.PREFIX, 8),
    Variant("SKULL", Affix.PREFIX, 9),
    Variant("INFESTED", Affix.PREFIX, 10),
    # Froglight
    Variant("OCHRE", Affix.PREFIX, 0),
    Variant("PEARLESCENT", Affix.PREFIX, 1),
    Variant("VERDANT", Affix.PREFIX, 2),
    # Armor Trims
    Variant("NETHERITE_UPGRADE", Affix.PREFIX, 0),
    Variant("BOLT_ARMOR_TRIM", Affix.PREFIX, 1),
    Variant("COAST_ARMOR_TRIM", Affix.PREFIX, 2),
    Variant("DUNE_ARMOR_TRIM", Affix.PREFIX, 3),
    Variant("EYE_ARMOR_TRIM", Affix.PREFIX, 4),
    Variant("FLOW_ARMOR_TRIM", Affix.PREFIX, 5),
    Variant("HOST_ARMOR_TRIM", Affix.PREFIX, 6),
    Variant("RAISER_ARMOR_TRIM", Affix.PREFIX, 7),
    Variant("RIB_ARMOR_TRIM", Affix.PREFIX, 8),
    Variant("SENTRY_ARMOR_TRIM", Affix.PREFIX, 9),
    Variant("SHAPER_ARMOR_TRIM", Affix.PREFIX, 10),
    Variant("SILENCE_ARMOR_TRIM", Affix.PREFIX, 11),
    Variant("SNOUT_ARMOR_TRIM", Affix.PREFIX, 12),
    Variant("SPIRE_ARMOR_TRIM", Affix.PREFIX, 13),
    Variant("TIDE_ARMOR_TRIM", Affix.PREFIX, 14),
    Variant("VEX_ARMOR_TRIM", Affix.PREFIX, 15),
    Variant("WARD_ARMOR_TRIM", Affix.PREFIX, 16),
    Variant("WAYFINDER_ARMOR_TRIM", Affix.PREFIX, 17),
    Variant("WILD_ARMOR_TRIM", Affix.PREFIX, 18),
    # Coral
    Variant("BRAIN", Affix.PREFIX, 0),
    Variant("BUBBLE", Affix.PREFIX, 1),
    Variant("FIRE", Affix.PREFIX, 2),
    Variant("HORN", Affix.PREFIX, 3),
    Variant("TUBE", Affix.PREFIX, 4),
    Variant("DEAD_BRAIN", Affix.PREFIX, 5),
    Variant("DEAD_BUBBLE", Affix.PREFIX, 6),
    Variant("DEAD_FIRE", Affix.PREFIX, 7),
    Variant("DEAD_HORN", Affix.PREFIX, 8),
    Variant("DEAD_TUBE", Affix.PREFIX, 9),
    # Torch/Lantern/Chain
    Variant("IRON", Affix.PREFIX, 0),
    Variant("SOUL", Affix.PREFIX, 1),
    Variant("COPPER", Affix.PREFIX, 2),
    Variant("EXPOSED_COPPER", Affix.PREFIX, 3),
    Variant("WEATHERED_COPPER", Affix.PREFIX, 4),
    Variant("OXIDIZED_COPPER", Affix.PREFIX, 5),
    Variant("WAXED_COPPER", Affix.PREFIX, 6),
    Variant("WAXED_EXPOSED_COPPER", Affix.PREFIX, 7),
    Variant("WAXED_WEATHERED_COPPER", Affix.PREFIX, 8),
    Variant("WAXED_OXIDIZED_COPPER", Affix.PREFIX, 9),
    Variant("REDSTONE", Affix.PREFIX, 10),
    # Lightning Rod
    Variant("EXPOSED", Affix.PREFIX, 0),
    Variant("WEATHERED", Affix.PREFIX, 1),
    Variant("OXIDIZED", Affix.PREFIX, 2),
    Variant("WAXED", Affix.PREFIX, 3),
    Variant("WAXED_EXPOSED", Affix.PREFIX, 4),
    Variant("WAXED_WEATHERED", Affix.PREFIX, 5),
    Variant("WAXED_OXIDIZED", Affix.PREFIX, 6),
    # Sapling/Leaves/Shelves
    Variant("OAK", Affix.PREFIX, 0),
    Variant("SPRUCE", Affix.PREFIX, 1),
    Variant("BIRCH", Affix.PREFIX, 2),
    Variant("JUNGLE", Affix.PREFIX, 3),
    Variant("ACACIA", Affix.PREFIX, 4),
    Variant("DARK_OAK", Affix.PREFIX, 5),
    Variant("MANGROVE", Affix.PREFIX, 6),
    Variant("CHERRY", Affix.PREFIX, 7),
    Variant("PALE_OAK", Affix.PREFIX, 8),
    Variant("AZALEA", Affix.PREFIX, 9),
    Variant("FLOWERING_AZALEA", Affix.PREFIX, 10),
    Variant("BAMBOO", Affix.PREFIX, 11),
    Variant("CRIMSON", Affix.PREFIX, 12),
    Variant("WARPED", Affix.PREFIX, 13),
    # Skulls/Heads
    Variant("SKELETON", Affix.PREFIX, 0),
    Variant("WITHER_SKELETON", Affix.PREFIX, 1),
    Variant("PLAYER", Affix.PREFIX, 2),
    Variant("ZOMBIE", Affix.PREFIX, 3),
    Variant("CREEPER", Affix.PREFIX, 4),
    Variant("PIGLIN", Affix.PREFIX, 5),
    Variant("DRAGON", Affix.PREFIX, 6),
    # Infested Blocks
    Variant("STONE", Affix.SUFFIX, 0),
    Variant("COBBLESTONE", Affix.SUFFIX, 1),
    Variant("STONE_BRICKS", Affix.SUFFIX, 2),
    Variant("MOSSY_STONE_BRICKS", Affix.SUFFIX, 3),
    Variant("CRACKED_STONE_BRICKS", Affix.SUFFIX, 4),
    Variant("CHISELED_STONE_BRICKS", Affix.SUFFIX, 5),
    Variant("DEEPSLATE", Affix.SUFFIX, 6),
    # Copper Golem Statue
    Variant("EXPOSED", Affix.PREFIX, 0),
    Variant("WEATHERED", Affix.PREFIX, 1),
    Variant("OXIDIZED", Affix.PREFIX, 2),
    Variant("WAXED", Affix.PREFIX, 3),
    Variant("WAXED_EXPOSED", Affix.PREFIX, 4),
    Variant("WAXED_WEATHERED", Affix.PREFIX, 5),
    Variant("WAXED_OXIDIZED", Affix.PREFIX, 6),
    # Food
    Variant("COOKED", Affix.PREFIX, 0),
    # Redstone
    Variant("TORCH", Affix.SUFFIX, 0),
    # Minecart
    Variant("HOPPER", Affix.PREFIX, 0),
    Variant("CHEST", Affix.PREFIX, 1),
    Variant("FURNACE", Affix.PREFIX, 2),
    Variant("TNT", Affix.PREFIX, 3),
]
