from category import Category
from family import Family
from variant import Affix, Variant

FAMILIES: list[Family] = [
    # Building Blocks
    # Wood
    Family(Category.BUILDING_BLOCKS, "OAK", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_OAK", 0),
    Family(Category.BUILDING_BLOCKS, "SPRUCE", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_SPRUCE", 0),
    Family(Category.BUILDING_BLOCKS, "BIRCH", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_BIRCH", 0),
    Family(Category.BUILDING_BLOCKS, "JUNGLE", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_JUNGLE", 0),
    Family(Category.BUILDING_BLOCKS, "ACACIA", 0),
    Family(Category.BUILDING_BLOCKS, "ACACIA", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_ACACIA", 0),
    Family(Category.BUILDING_BLOCKS, "DARK_OAK", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_DARK_OAK", 0),
    Family(Category.BUILDING_BLOCKS, "MANGROVE", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_MANGROVE", 0),
    Family(Category.BUILDING_BLOCKS, "CHERRY", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_CHERRY", 0),
    Family(Category.BUILDING_BLOCKS, "PALE_OAK", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_PALE_OAK", 0),
    # Bamboo
    Family(Category.BUILDING_BLOCKS, "BAMBOO", 0),
    Family(Category.BUILDING_BLOCKS, "BAMBOO_BLOCK", 0),
    Family(Category.BUILDING_BLOCKS, "BAMBOO_MOSAIC", 0),
    # Nether Wood
    Family(Category.BUILDING_BLOCKS, "CRIMSON", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_CRIMSON", 0),
    Family(Category.BUILDING_BLOCKS, "WARPED", 0),
    Family(Category.BUILDING_BLOCKS, "STRIPPED_WARPED", 0),
    # Stone & Rock
    Family(Category.BUILDING_BLOCKS, "ANDESITE", 0),
    Family(Category.BUILDING_BLOCKS, "BASALT", 0),
    Family(Category.BUILDING_BLOCKS, "BLACKSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "CALCITE", 0),
    Family(Category.BUILDING_BLOCKS, "CHISELED_RED_SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "CHISELED_SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "COBBLESTONE", 0),
    Family(Category.BUILDING_BLOCKS, "CRACKED_POLISHED_BLACKSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "CRACKED_POLISHED_BLACKSTONE_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "CUT_RED_SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "CUT_SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "DIORITE", 0),
    Family(Category.BUILDING_BLOCKS, "DRIPSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "END_STONE", 0),
    Family(Category.BUILDING_BLOCKS, "GILDED_BLACKSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "GLOWSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "GRANITE", 0),
    Family(Category.BUILDING_BLOCKS, "LODESTONE", 0),
    Family(Category.BUILDING_BLOCKS, "MOSSY_COBBLESTONE", 0),
    Family(Category.BUILDING_BLOCKS, "MOSSY_STONE_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "MOSSY_STONE_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_ANDESITE", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_BASALT", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_BLACKSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_DIORITE", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_GRANITE", 0),
    Family(Category.BUILDING_BLOCKS, "REDSTONE_WIRE", 0),
    Family(Category.BUILDING_BLOCKS, "RED_SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_BASALT", 0),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_RED_SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_SANDSTONE", 0),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_STONE", 0),
    Family(Category.BUILDING_BLOCKS, "STONE", 0),
    Family(Category.BUILDING_BLOCKS, "STONE_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "STONE_BRICKS", 0),
    # Deepslate
    Family(Category.BUILDING_BLOCKS, "CHISELED_DEEPSLATE", 0),
    Family(Category.BUILDING_BLOCKS, "COBBLED_DEEPSLATE", 0),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE", 0),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_COAL_ORE", 0),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_TILES", 0),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_TILE", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_DEEPSLATE", 0),
    Family(Category.BUILDING_BLOCKS, "REINFORCED_DEEPSLATE", 0),
    # Tuff
    Family(Category.BUILDING_BLOCKS, "CHISELED_TUFF", 0),
    Family(Category.BUILDING_BLOCKS, "CHISELED_TUFF_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_TUFF", 0),
    Family(Category.BUILDING_BLOCKS, "TUFF", 0),
    Family(Category.BUILDING_BLOCKS, "TUFF_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "TUFF_BRICK", 0),
    # Bricks
    Family(Category.BUILDING_BLOCKS, "BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "CINNABAR_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "CINNABAR_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "MUD_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "MUD_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "NETHER_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "NETHER_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "PRISMARINE_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "PRISMARINE_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "QUARTZ_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "QUARTZ_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "RED_NETHER_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "RESIN_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "RESIN_BRICK", 0),
    Family(Category.BUILDING_BLOCKS, "SULFUR_BRICKS", 0),
    Family(Category.BUILDING_BLOCKS, "SULFUR_BRICK", 0),
    # Copper
    Family(Category.BUILDING_BLOCKS, "COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "CUT_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "CHISELED_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "COPPER_BULB", 0),
    Family(Category.BUILDING_BLOCKS, "DEEPSLATE_COPPER_ORE", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_CUT_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_EXPOSED_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_EXPOSED_COPPER_GOLEM_STATUE", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_EXPOSED_CUT_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_OXIDIZED_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_OXIDIZED_COPPER_GOLEM_STATUE", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_OXIDIZED_CUT_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_CHISELED_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_COPPER_GOLEM_STATUE", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_CUT_COPPER", 0),
    Family(Category.BUILDING_BLOCKS, "WEATHERED_CUT_COPPER", 0),
    # Minerals
    Family(Category.BUILDING_BLOCKS, "AMETHYST", 0),
    Family(Category.BUILDING_BLOCKS, "COAL", 0),
    Family(Category.BUILDING_BLOCKS, "GOLD", 0),
    Family(Category.BUILDING_BLOCKS, "IRON", 0),
    Family(Category.BUILDING_BLOCKS, "LAPIS", 0),
    # Ocean
    Family(Category.BUILDING_BLOCKS, "DARK_PRISMARINE", 0),
    Family(Category.BUILDING_BLOCKS, "PRISMARINE", 0),
    Family(Category.BUILDING_BLOCKS, "SEA_LANTERN", 0),
    Family(Category.BUILDING_BLOCKS, "SEA_PICKLE", 0),
    # Nether
    Family(Category.BUILDING_BLOCKS, "CRYING_OBSIDIAN", 0),
    Family(Category.BUILDING_BLOCKS, "MAGMA", 0),
    Family(Category.BUILDING_BLOCKS, "NETHER", 0),
    Family(Category.BUILDING_BLOCKS, "NETHERRACK", 0),
    Family(Category.BUILDING_BLOCKS, "NETHER_PORTAL", 0),
    Family(Category.BUILDING_BLOCKS, "NETHER_WART", 0),
    Family(Category.BUILDING_BLOCKS, "OBSIDIAN", 0),
    Family(Category.BUILDING_BLOCKS, "QUARTZ", 0),
    Family(Category.BUILDING_BLOCKS, "SMOOTH_QUARTZ", 0),
    Family(Category.BUILDING_BLOCKS, "SOUL", 0),
    # End
    Family(Category.BUILDING_BLOCKS, "CHORUS", 0),
    Family(Category.BUILDING_BLOCKS, "PURPUR", 0),
    # Glass
    Family(Category.BUILDING_BLOCKS, "GLASS", 0),
    Family(Category.BUILDING_BLOCKS, "TINTED_GLASS", 0),
    # Other Natural Blocks
    Family(Category.BUILDING_BLOCKS, "CHISELED_CINNABAR", 0),
    Family(Category.BUILDING_BLOCKS, "CINNABAR", 0),
    Family(Category.BUILDING_BLOCKS, "CLAY", 0),
    Family(Category.BUILDING_BLOCKS, "MUD", 0),
    Family(Category.BUILDING_BLOCKS, "MUDDY_MANGROVE", 0),
    Family(Category.BUILDING_BLOCKS, "PACKED_MUD", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_CINNABAR", 0),
    Family(Category.BUILDING_BLOCKS, "POLISHED_SULFUR", 0),
    Family(Category.BUILDING_BLOCKS, "RESIN", 0),
    Family(Category.BUILDING_BLOCKS, "SULFUR_SPIKE", 0),
    # Special & Decorative
    Family(Category.BUILDING_BLOCKS, "ANVIL", 0),
    Family(Category.BUILDING_BLOCKS, "ARMOR_STAND", 0),
    Family(Category.BUILDING_BLOCKS, "BARREL", 0),
    Family(Category.BUILDING_BLOCKS, "BEACON", 0),
    Family(Category.BUILDING_BLOCKS, "BEDROCK", 0),
    Family(Category.BUILDING_BLOCKS, "BEE", 0),
    Family(Category.BUILDING_BLOCKS, "BONE", 0),
    Family(Category.BUILDING_BLOCKS, "BOOKSHELF", 0),
    Family(Category.BUILDING_BLOCKS, "BRAIN_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "BUBBLE_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "CAMPFIRE", 0),
    Family(Category.BUILDING_BLOCKS, "CANDLE", 0),
    Family(Category.BUILDING_BLOCKS, "CHISELED", 0),
    Family(Category.BUILDING_BLOCKS, "COBWEB", 0),
    Family(Category.BUILDING_BLOCKS, "CORNFLOWER", 0),
    Family(Category.BUILDING_BLOCKS, "DEAD_BRAIN_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "DEAD_BUBBLE_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "DEAD_FIRE_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "DEAD_HORN_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "DEAD_TUBE_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "DECORATED_POT", 0),
    Family(Category.BUILDING_BLOCKS, "FIRE", 0),
    Family(Category.BUILDING_BLOCKS, "FIRE_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "FLOWER", 0),
    Family(Category.BUILDING_BLOCKS, "FROGLIGHT", 0),
    Family(Category.BUILDING_BLOCKS, "FROGLIGHT", 0),
    Family(Category.BUILDING_BLOCKS, "GRASS", 0),
    Family(Category.BUILDING_BLOCKS, "HAY", 0),
    Family(Category.BUILDING_BLOCKS, "HEAVY_WEIGHTED_PRESSURE_PLATE", 0),
    Family(Category.BUILDING_BLOCKS, "HONEY", 0),
    Family(Category.BUILDING_BLOCKS, "HORN_CORAL", 0),
    Family(Category.BUILDING_BLOCKS, "ICE", 0),
    Family(Category.BUILDING_BLOCKS, "INFESTED", 0),
    Family(Category.BUILDING_BLOCKS, "JACK_O_LANTERN", 0),
    Family(Category.BUILDING_BLOCKS, "LIGHT", 0),
    Family(Category.BUILDING_BLOCKS, "LIGHT_WEIGHTED_PRESSURE_PLATE", 0),
    Family(Category.BUILDING_BLOCKS, "MOSS", 0),
    Family(Category.BUILDING_BLOCKS, "MUSHROOM", 0),
    Family(Category.BUILDING_BLOCKS, "NOTE", 0),
    Family(Category.BUILDING_BLOCKS, "OCHRE", 0),
    Family(Category.BUILDING_BLOCKS, "PACKED_ICE", 0),
    Family(Category.BUILDING_BLOCKS, "PALE_MOSS", 0),
    Family(Category.BUILDING_BLOCKS, "PEARLESCENT", 0),
    Family(Category.BUILDING_BLOCKS, "PILLAR", 0),
    Family(Category.BUILDING_BLOCKS, "RESPAWN_ANCHOR", 0),
    Family(Category.BUILDING_BLOCKS, "SHROOMLIGHT", 0),
    Family(Category.BUILDING_BLOCKS, "SLIME", 0),
    Family(Category.BUILDING_BLOCKS, "SNOW", 0),
    Family(Category.BUILDING_BLOCKS, "SPONGE", 0),
    Family(Category.BUILDING_BLOCKS, "TNT", 0),
    Family(Category.BUILDING_BLOCKS, "TORCH", 0),
    Family(Category.BUILDING_BLOCKS, "TRAPPED_CHEST", 0),
    Family(Category.BUILDING_BLOCKS, "TRIAL", 0),
    Family(Category.BUILDING_BLOCKS, "TRIAL_SPAWNER", 0),
    Family(Category.BUILDING_BLOCKS, "TURTLE_EGG", 0),
    Family(Category.BUILDING_BLOCKS, "VAULT", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_EXPOSED_LIGHTNING_ROD", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_OXIDIZED_LIGHTNING_ROD", 0),
    Family(Category.BUILDING_BLOCKS, "WAXED_WEATHERED_LIGHTNING_ROD", 0),
    Family(Category.BUILDING_BLOCKS, "WET_SPONGE", 0),
    Family(Category.BUILDING_BLOCKS, "WILDFLOWERS", 0),
    Family(Category.BUILDING_BLOCKS, "WITHER_ROSE", 0),
    Family(Category.BUILDING_BLOCKS, "WOLF_ARMOR", 0),
    # Colored Blocks
    # Colored Blocks
    Family(Category.COLORED_BLOCKS, "BANNER", 0),
    Family(Category.COLORED_BLOCKS, "BED", 0),
    Family(Category.COLORED_BLOCKS, "CANDLE_CAKE", 0),
    Family(Category.COLORED_BLOCKS, "CARPET", 0),
    Family(Category.COLORED_BLOCKS, "CONCRETE", 0),
    Family(Category.COLORED_BLOCKS, "CONCRETE_POWDER", 0),
    Family(Category.COLORED_BLOCKS, "DYE", 0),
    Family(Category.COLORED_BLOCKS, "GLAZED_TERRACOTTA", 0),
    Family(Category.COLORED_BLOCKS, "HARNESS", 0),
    Family(Category.COLORED_BLOCKS, "SHULKER_BOX", 0),
    Family(Category.COLORED_BLOCKS, "STAINED_GLASS", 0),
    Family(Category.COLORED_BLOCKS, "STAINED_GLASS_PANE", 0),
    Family(Category.COLORED_BLOCKS, "TERRACOTTA", 0),
    Family(Category.COLORED_BLOCKS, "WALL_BANNER", 0),
    Family(Category.COLORED_BLOCKS, "WOOL", 0),
    # Natural Blocks
    # Soils & Terrain
    Family(Category.NATURAL_BLOCKS, "COARSE_DIRT", 0),
    Family(Category.NATURAL_BLOCKS, "DIRT", 0),
    Family(Category.NATURAL_BLOCKS, "DIRT_PATH", 0),
    Family(Category.NATURAL_BLOCKS, "FARMLAND", 0),
    Family(Category.NATURAL_BLOCKS, "GRAVEL", 0),
    Family(Category.NATURAL_BLOCKS, "MYCELIUM", 0),
    Family(Category.NATURAL_BLOCKS, "PODZOL", 0),
    Family(Category.NATURAL_BLOCKS, "RED_SAND", 0),
    Family(Category.NATURAL_BLOCKS, "ROOTED_DIRT", 0),
    Family(Category.NATURAL_BLOCKS, "SAND", 0),
    Family(Category.NATURAL_BLOCKS, "SEAGRASS", 0),
    Family(Category.NATURAL_BLOCKS, "SHORT_DRY_GRASS", 0),
    Family(Category.NATURAL_BLOCKS, "SHORT_GRASS", 0),
    Family(Category.NATURAL_BLOCKS, "SUSPICIOUS_GRAVEL", 0),
    Family(Category.NATURAL_BLOCKS, "SUSPICIOUS_SAND", 0),
    Family(Category.NATURAL_BLOCKS, "TALL_DRY_GRASS", 0),
    Family(Category.NATURAL_BLOCKS, "TALL_GRASS", 0),
    Family(Category.NATURAL_BLOCKS, "TALL_SEAGRASS", 0),
    # Ores & Resources
    Family(Category.NATURAL_BLOCKS, "ANCIENT_DEBRIS", 0),
    Family(Category.NATURAL_BLOCKS, "COAL", 0),
    Family(Category.NATURAL_BLOCKS, "COAL_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "DIAMOND_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "EMERALD_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "GOLD_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "IRON_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "LAPIS_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "NETHER_QUARTZ", 0),
    Family(Category.NATURAL_BLOCKS, "REDSTONE_ORE", 0),
    Family(Category.NATURAL_BLOCKS, "SPORE_BLOSSOM", 0),
    # Trees & Foliage
    Family(Category.NATURAL_BLOCKS, "AZALEA", 0),
    Family(Category.NATURAL_BLOCKS, "FLOWERING_AZALEA", 0),
    Family(Category.NATURAL_BLOCKS, "HANGING_ROOTS", 0),
    Family(Category.NATURAL_BLOCKS, "MANGROVE_PROPAGULE", 0),
    Family(Category.NATURAL_BLOCKS, "MOSS_BLOCK", 0),
    Family(Category.NATURAL_BLOCKS, "MOSS_CARPET", 0),
    Family(Category.NATURAL_BLOCKS, "WARPED_ROOTS", 0),
    # Flowers & Plants
    Family(Category.NATURAL_BLOCKS, "ALLIUM", 0),
    Family(Category.NATURAL_BLOCKS, "BLUE_ORCHID", 0),
    Family(Category.NATURAL_BLOCKS, "BUSH", 0),
    Family(Category.NATURAL_BLOCKS, "CACTUS_FLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "CHORUS_FLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "DANDELION", 0),
    Family(Category.NATURAL_BLOCKS, "DEAD_BUSH", 0),
    Family(Category.NATURAL_BLOCKS, "FERN", 0),
    Family(Category.NATURAL_BLOCKS, "FIREFLY_BUSH", 0),
    Family(Category.NATURAL_BLOCKS, "LARGE_FERN", 0),
    Family(Category.NATURAL_BLOCKS, "LILAC", 0),
    Family(Category.NATURAL_BLOCKS, "ORANGE_TULIP", 0),
    Family(Category.NATURAL_BLOCKS, "PEONY", 0),
    Family(Category.NATURAL_BLOCKS, "PINK_PETALS", 0),
    Family(Category.NATURAL_BLOCKS, "PINK_TULIP", 0),
    Family(Category.NATURAL_BLOCKS, "POPPY", 0),
    Family(Category.NATURAL_BLOCKS, "RED_TULIP", 0),
    Family(Category.NATURAL_BLOCKS, "ROSE_BUSH", 0),
    Family(Category.NATURAL_BLOCKS, "SUNFLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "SWEET_BERRY_BUSH", 0),
    Family(Category.NATURAL_BLOCKS, "TORCHFLOWER", 0),
    Family(Category.NATURAL_BLOCKS, "WHITE_TULIP", 0),
    # Mushrooms & Nether Vegetation
    Family(Category.NATURAL_BLOCKS, "BROWN_MUSHROOM", 0),
    Family(Category.NATURAL_BLOCKS, "NETHER_SPROUTS", 0),
    Family(Category.NATURAL_BLOCKS, "RED_MUSHROOM", 0),
    Family(Category.NATURAL_BLOCKS, "TWISTING_VINES", 0),
    Family(Category.NATURAL_BLOCKS, "WARPED_FUNGUS", 0),
    Family(Category.NATURAL_BLOCKS, "WEEPING_VINES", 0),
    # Ocean & Coral
    Family(Category.NATURAL_BLOCKS, "CORAL", 0),
    Family(Category.NATURAL_BLOCKS, "FROGSPAWN", 0),
    Family(Category.NATURAL_BLOCKS, "KELP", 0),
    Family(Category.NATURAL_BLOCKS, "LILY_PAD", 0),
    Family(Category.NATURAL_BLOCKS, "TUBE_CORAL", 0),
    # Ice & Snow
    Family(Category.NATURAL_BLOCKS, "BLUE_ICE", 0),
    Family(Category.NATURAL_BLOCKS, "SNOWBALL", 0),
    # Caves & Geodes
    Family(Category.NATURAL_BLOCKS, "LARGE_AMETHYST_BUD", 0),
    Family(Category.NATURAL_BLOCKS, "MEDIUM_AMETHYST_BUD", 0),
    Family(Category.NATURAL_BLOCKS, "POINTED_DRIPSTONE", 0),
    Family(Category.NATURAL_BLOCKS, "SMALL_AMETHYST_BUD", 0),
    # Sculk
    Family(Category.NATURAL_BLOCKS, "SCULK", 0),
    Family(Category.NATURAL_BLOCKS, "SCULK_CATALYST", 0),
    Family(Category.NATURAL_BLOCKS, "SCULK_SHRIEKER", 0),
    Family(Category.NATURAL_BLOCKS, "SCULK_VEIN", 0),
    # Special Natural
    Family(Category.NATURAL_BLOCKS, "AZURE_BLUET", 0),
    Family(Category.NATURAL_BLOCKS, "BEE_NEST", 0),
    Family(Category.NATURAL_BLOCKS, "BIG_DRIPLEAF", 0),
    Family(Category.NATURAL_BLOCKS, "CACTUS", 0),
    Family(Category.NATURAL_BLOCKS, "CAVE", 0),
    Family(Category.NATURAL_BLOCKS, "CHORUS_PLANT", 0),
    Family(Category.NATURAL_BLOCKS, "CLOSED_EYEBLOSSOM", 0),
    Family(Category.NATURAL_BLOCKS, "COCOA", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_BARS", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_CHAIN", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_CHEST", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_DOOR", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_GRATE", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_LANTERN", 0),
    Family(Category.NATURAL_BLOCKS, "COPPER_TRAPDOOR", 0),
    Family(Category.NATURAL_BLOCKS, "DRIED_GHAST", 0),
    Family(Category.NATURAL_BLOCKS, "END_PORTAL_FRAME", 0),
    Family(Category.NATURAL_BLOCKS, "END_STONE_BRICK", 0),
    Family(Category.NATURAL_BLOCKS, "END_STONE_BRICKS", 0),
    Family(Category.NATURAL_BLOCKS, "EXPOSED_CHISELED_COPPER", 0),
    Family(Category.NATURAL_BLOCKS, "EXPOSED_CUT_COPPER", 0),
    Family(Category.NATURAL_BLOCKS, "FLETCHING_TABLE", 0),
    Family(Category.NATURAL_BLOCKS, "GLOW_LICHEN", 0),
    Family(Category.NATURAL_BLOCKS, "INFESTED_CHISELED_STONE_BRICKS", 0),
    Family(Category.NATURAL_BLOCKS, "INFESTED_COBBLESTONE", 0),
    Family(Category.NATURAL_BLOCKS, "INFESTED_CRACKED_STONE_BRICKS", 0),
    Family(Category.NATURAL_BLOCKS, "LEAF_LITTER", 0),
    Family(Category.NATURAL_BLOCKS, "LIGHTNING_ROD", 0),
    Family(Category.NATURAL_BLOCKS, "LILY_OF_THE_VALLEY", 0),
    Family(Category.NATURAL_BLOCKS, "MELON", 0),
    Family(Category.NATURAL_BLOCKS, "OPEN_EYEBLOSSOM", 0),
    Family(Category.NATURAL_BLOCKS, "OXEYE_DAISY", 0),
    Family(Category.NATURAL_BLOCKS, "PITCHER_PLANT", 0),
    Family(Category.NATURAL_BLOCKS, "POTATO", 0),
    Family(Category.NATURAL_BLOCKS, "PUMPKIN", 0),
    Family(Category.NATURAL_BLOCKS, "SMALL_DRIPLEAF", 0),
    Family(Category.NATURAL_BLOCKS, "VINE", 0),
    Family(Category.NATURAL_BLOCKS, "WITHER_ROSE", 0),
    # Functional Blocks
    # Storage & Display
    Family(Category.FUNCTIONAL_BLOCKS, "BARREL", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "CHEST", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "ENDER_CHEST", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "GLOW_ITEM_FRAME", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "ITEM_FRAME", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "PAINTING", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "SHULKER_BOX", 0),
    # Workstations
    Family(Category.FUNCTIONAL_BLOCKS, "CARTOGRAPHY_TABLE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "CRAFTING_TABLE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "ENCHANTING_TABLE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "GRINDSTONE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "LECTERN", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "LOOM", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "SMITHING_TABLE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "STONECUTTER", 0),
    # Processing
    Family(Category.FUNCTIONAL_BLOCKS, "BLAST_FURNACE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "BREWING_STAND", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "CAULDRON", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "COMPOSTER", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "FURNACE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "SMOKER", 0),
    # Lighting
    Family(Category.FUNCTIONAL_BLOCKS, "CAMPFIRE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "LANTERN", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "SOUL_CAMPFIRE", 0),
    # Copper
    Family(Category.FUNCTIONAL_BLOCKS, "COPPER_GOLEM_STATUE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "OXIDIZED_CHISELED_COPPER", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "OXIDIZED_CUT_COPPER", 0),
    # Utility & Decoration
    Family(Category.FUNCTIONAL_BLOCKS, "ANVIL", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "ARMOR_STAND", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "BEACON", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "BELL", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "CHIPPED_ANVIL", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "CONDUIT", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "DECORATED_POT", 0),
    # Special Functional
    Family(Category.FUNCTIONAL_BLOCKS, "BEEHIVE", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "CHISELED_BOOKSHELF", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "DRAGON_EGG", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "END_CRYSTAL", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "FLOWER_POT", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "JUKEBOX", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "PALE_HANGING_MOSS", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "PETRIFIED_OAK_SLAB", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "PITCHER_CROP", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "POLISHED_BLACKSTONE_BRICK", 0),
    Family(Category.FUNCTIONAL_BLOCKS, "POLISHED_BLACKSTONE_BRICKS", 0),
    # Redstone Blocks
    # Redstone Power
    Family(Category.REDSTONE_BLOCKS, "REDSTONE", 0),
    Family(Category.REDSTONE_BLOCKS, "REDSTONE_BLOCK", 0),
    Family(Category.REDSTONE_BLOCKS, "REDSTONE_LAMP", 0),
    # Redstone Machines
    Family(Category.REDSTONE_BLOCKS, "CRAFTER", 0),
    Family(Category.REDSTONE_BLOCKS, "CREAKING_HEART", 0),
    Family(Category.REDSTONE_BLOCKS, "DISPENSER", 0),
    Family(Category.REDSTONE_BLOCKS, "DROPPER", 0),
    Family(Category.REDSTONE_BLOCKS, "HOPPER", 0),
    Family(Category.REDSTONE_BLOCKS, "PISTON", 0),
    Family(Category.REDSTONE_BLOCKS, "STICKY_PISTON", 0),
    # Redstone Logic & Sensors
    Family(Category.REDSTONE_BLOCKS, "CALIBRATED_SCULK_SENSOR", 0),
    Family(Category.REDSTONE_BLOCKS, "COMPARATOR", 0),
    Family(Category.REDSTONE_BLOCKS, "DAYLIGHT_DETECTOR", 0),
    Family(Category.REDSTONE_BLOCKS, "NOTE_BLOCK", 0),
    Family(Category.REDSTONE_BLOCKS, "OBSERVER", 0),
    Family(Category.REDSTONE_BLOCKS, "REPEATER", 0),
    Family(Category.REDSTONE_BLOCKS, "SCULK_SENSOR", 0),
    Family(Category.REDSTONE_BLOCKS, "TARGET", 0),
    # Redstone Controls & Transport
    Family(Category.REDSTONE_BLOCKS, "LEVER", 0),
    Family(Category.REDSTONE_BLOCKS, "RAIL", 0),
    Family(Category.REDSTONE_BLOCKS, "TRIPWIRE", 0),
    Family(Category.REDSTONE_BLOCKS, "TRIPWIRE_HOOK", 0),
    # Redstone Misc
    Family(Category.REDSTONE_BLOCKS, "CRAFTING_TABLE", 0),
    Family(Category.REDSTONE_BLOCKS, "TNT", 0),
    # Tools And Utilities
    # Tools
    Family(Category.TOOLS_AND_UTILITIES, "AXE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AXE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HOE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PICKAXE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHOVEL", 0),
    # Rails
    Family(Category.TOOLS_AND_UTILITIES, "ACTIVATOR", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ALLAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AMETHYST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AMETHYST_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AMETHYST_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "APPLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMADILLO", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMADILLO", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMADILLO_SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMADILLO_SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMADILLO_SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMOR_STAND", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMOR_STAND", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMOR_STAND", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "ARMOR_TRIM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARMOR_TRIM", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ARROW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ARROW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AXOLOTL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AXOLOTL", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "AXOLOTL_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AXOLOTL_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "AXOLOTL_BUCKET", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "BANNER_PATTERN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BARRIER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BARRIER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BARRIER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BAT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BEE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLADE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_POWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_POWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_POWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_POWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_POWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BLAZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BOGGED", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "BOLT_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BONE_MEAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BONE_MEAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BONE_MEAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BONE_MEAL", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BOOKSHELF", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "BORDURE_INDENTED_BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BOW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BOWL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BOWL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BREEZE_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BRICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BRICK", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "BRUSH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BRUSH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BRUSH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BRUSH", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BUBBLE_COLUMN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUBBLE_COLUMN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUBBLE_COLUMN", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "BUNDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUNDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUNDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "BUNDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAMEL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CARROT_ON_A_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CARROT_ON_A_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAVE_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAVE_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAVE_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CAVE_SPIDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHAINMAIL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHAIN_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHAIN_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHAIN_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHARCOAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHARCOAL", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "CHEST_MINECART", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CHEST_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "CHICKEN", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "CHISELED_BOOKSHELF", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "CHISELED_QUARTZ", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CINNABAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CINNABAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLAY_BALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLAY_BALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COAL", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "COAST_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "COD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COD", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "COD_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COD_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COMMAND_BLOCK", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "COMMAND_BLOCK_MINECART", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COMMAND_BLOCK_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COPPER_NUGGET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "COW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CREAKING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CREEPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CREEPER", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "CREEPER_BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "CREEPER_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "CROSSBOW", 0),
    # Technical
    Family(Category.TOOLS_AND_UTILITIES, "DEBUG_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DEBUG_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DEBUG_STICK", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "DIAMOND", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DIAMOND", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DIAMOND", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DIAMOND", 0),
    # Music
    Family(Category.TOOLS_AND_UTILITIES, "DISC_FRAGMENT", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "DOLPHIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DONKEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON_BREATH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON_BREATH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON_BREATH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON_BREATH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DRAGON_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "DROWNED", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "DUNE_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ECHO_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ECHO_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ECHO_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ECHO_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ECHO_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EGG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EGG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EGG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ELDER_GUARDIAN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ELYTRA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ELYTRA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EMERALD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EMERALD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EMERALD", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "ENCHANTED_BOOK", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ENCHANTED_GOLDEN_APPLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDERMAN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDERMITE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_DRAGON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_DRAGON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_EYE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_EYE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_EYE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_EYE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_EYE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_PEARL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_PEARL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_PEARL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_PEARL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ENDER_PEARL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_CRYSTAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_GATEWAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_GATEWAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_GATEWAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_PORTAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_PORTAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_PORTAL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "END_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EVOKER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EXPERIENCE_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EXPERIENCE_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "EXPERIENCE_BOTTLE", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "EYE_ARMOR_TRIM_SMITHING_TEMPLATE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FERMENTED_SPIDER_EYE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FERMENTED_SPIDER_EYE", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "FIELD_MASONED_BANNER_PATTERN", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "FILLED_MAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FILLED_MAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FILLED_MAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FILLED_MAP", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FIRE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIRE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_ROCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_ROCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_ROCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_ROCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIREWORK_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIRE_CHARGE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIRE_CHARGE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FIRE_CHARGE", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "FISHING_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FISHING_ROD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FISHING_ROD", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FLINT", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "FLINT_AND_STEEL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FLINT_AND_STEEL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FLINT_AND_STEEL", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "FLOWER_BANNER_PATTERN", 0),
    Family(
        Category.TOOLS_AND_UTILITIES, "FLOW_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    Family(Category.TOOLS_AND_UTILITIES, "FLOW_BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "FOX", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FROG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FROSTED_ICE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FROSTED_ICE", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "FURNACE_MINECART", 0),
    Family(Category.TOOLS_AND_UTILITIES, "FURNACE_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "GHAST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GHAST_TEAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GHAST_TEAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLASS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLASS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLASS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLASS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLISTERING_MELON_SLICE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLISTERING_MELON_SLICE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOWSTONE_DUST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOWSTONE_DUST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GLOW_SQUID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOAT", 0),
    # Music
    Family(Category.TOOLS_AND_UTILITIES, "GOAT_HORN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOAT_HORN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOAT_HORN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOAT_HORN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOAT_HORN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "GOLD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLDEN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLDEN_APPLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLDEN_CARROT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLD_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLD_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GOLD_NUGGET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GUARDIAN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GUNPOWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GUNPOWDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "GUNPOWDER", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "GUSTER_BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "HAPPY_GHAST", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HEART_OF_THE_SEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HEART_OF_THE_SEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HEART_OF_THE_SEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HEART_OF_THE_SEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HEAVY_CORE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HEAVY_CORE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HOGLIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HONEYCOMB", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HONEYCOMB_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HONEY_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HONEY_BOTTLE", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "HOPPER_MINECART", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HOPPER_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "HORSE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HORSE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HORSE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "HORSE", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "HOST_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "HUSK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "INK_SAC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON_GOLEM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "IRON_NUGGET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ITEM_FRAME", 0),
    Family(Category.TOOLS_AND_UTILITIES, "JIGSAW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "JIGSAW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "JIGSAW", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "KNOWLEDGE_BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "KNOWLEDGE_BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "KNOWLEDGE_BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "KNOWLEDGE_BOOK", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "LADDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LADDER", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "LAPIS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAPIS_LAZULI", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAPIS_LAZULI", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAPIS_LAZULI", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAVA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAVA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAVA", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "LAVA_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LAVA_BUCKET", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "LEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LEAD", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "LEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LEATHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LINGERING_POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LINGERING_POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LINGERING_POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "LLAMA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MACE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAGMA_CREAM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAGMA_CREAM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAGMA_CREAM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAGMA_CUBE", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "MAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MAP", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "MILK_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MILK_BUCKET", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "MINECART", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MINECART", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MINECART", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "MOJANG_BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "MOOSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MOVING_PISTON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MOVING_PISTON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MULE", 0),
    # Music
    Family(Category.TOOLS_AND_UTILITIES, "MUSIC_DISC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MUSIC_DISC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MUSIC_DISC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MUSIC_DISC", 0),
    Family(Category.TOOLS_AND_UTILITIES, "MUSIC_DISC", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "NAME_TAG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAME_TAG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAME_TAG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAME_TAG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAME_TAG", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NAUTILUS_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE_INGOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE_SCRAP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHERITE_SCRAP", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "NETHERITE_UPGRADE_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "NETHER_BRICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHER_BRICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHER_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHER_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "NETHER_STAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OCELOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_BOTTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_TRIAL_KEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_TRIAL_KEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "OMINOUS_TRIAL_KEY", 0),
    # Decoration
    Family(Category.TOOLS_AND_UTILITIES, "PAINTING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAINTING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAINTING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAINTING", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "PANDA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PAPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PARCHED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PARROT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PHANTOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PHANTOM_MEMBRANE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PHANTOM_MEMBRANE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PHANTOM_MEMBRANE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PHANTOM_MEMBRANE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIG", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN_BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN_BRUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PIGLIN_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PILLAGER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PISTON_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PISTON_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PLAYER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PLAYER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PLAYER_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POLAR_BEAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTATOES", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTENT_SULFUR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ACACIA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ACACIA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ALLIUM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ALLIUM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_AZALEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_AZALEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_AZURE_BLUET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_AZURE_BLUET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BAMBOO", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BAMBOO", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BIRCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BIRCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BLUE_ORCHID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BLUE_ORCHID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BROWN_MUSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_BROWN_MUSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CACTUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CACTUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CHERRY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CHERRY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CLOSED_EYEBLOSSOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CLOSED_EYEBLOSSOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CORNFLOWER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CORNFLOWER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON_FUNGUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON_FUNGUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON_ROOTS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_CRIMSON_ROOTS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DANDELION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DANDELION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DARK_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DARK_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DEAD_BUSH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_DEAD_BUSH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_FERN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_FERN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_FLOWERING_AZALEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_FLOWERING_AZALEA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_GOLDEN_DANDELION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_GOLDEN_DANDELION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_JUNGLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_JUNGLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_JUNGLE_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_JUNGLE_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_LILY_OF_THE_VALLEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_LILY_OF_THE_VALLEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_MANGROVE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_MANGROVE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_MANGROVE_PROPAGULE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_MANGROVE_PROPAGULE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OAK_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OAK_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OPEN_EYEBLOSSOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OPEN_EYEBLOSSOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ORANGE_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_ORANGE_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OXEYE_DAISY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_OXEYE_DAISY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PALE_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PALE_OAK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PALE_OAK_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PALE_OAK_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PINK_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_PINK_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_POPPY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_POPPY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_RED_MUSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_RED_MUSHROOM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_RED_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_RED_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_SPRUCE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_SPRUCE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_SPRUCE_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_SPRUCE_SAPLING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_TORCHFLOWER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_TORCHFLOWER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED_FUNGUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED_FUNGUS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED_ROOTS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WARPED_ROOTS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WHITE_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WHITE_TULIP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WITHER_ROSE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTED_WITHER_ROSE", 0),
    # Pottery
    Family(Category.TOOLS_AND_UTILITIES, "POTTERY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POTTERY_SHERD", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "POWDER_SNOW", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "POWDER_SNOW_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "POWDER_SNOW_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "PRISMARINE_CRYSTALS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PRISMARINE_CRYSTALS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PRISMARINE_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PRISMARINE_SHARD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PUFFERFISH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PUFFERFISH", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "PUFFERFISH_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "PUFFERFISH_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "QUARTZ", 0),
    Family(Category.TOOLS_AND_UTILITIES, "QUARTZ", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_FOOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_FOOT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_HIDE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_HIDE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_HIDE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RABBIT_HIDE", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "RAISER_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "RAVAGER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RAW_COPPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RAW_COPPER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RAW_GOLD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RAW_GOLD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RAW_IRON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RAW_IRON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RECOVERY_COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RECOVERY_COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RECOVERY_COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RECOVERY_COMPASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REDSTONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REDSTONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REDSTONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REDSTONE_WALL_TORCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REPEATING_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REPEATING_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "REPEATING_COMMAND_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RESIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RESIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RESIN_CLUMP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "RESIN_CLUMP", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "RIB_ARMOR_TRIM_SMITHING_TEMPLATE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ROTTEN_FLESH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SADDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SADDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SADDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SADDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SADDLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SALMON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SALMON", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "SALMON_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SALMON_BUCKET", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "SCAFFOLDING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SCAFFOLDING", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SCUTE", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    Family(
        Category.TOOLS_AND_UTILITIES, "SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "SHEARS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHEARS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHEARS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHEARS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHEARS", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SHEEP", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHIELD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHULKER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHULKER_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHULKER_SHELL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SHULKER_SHELL", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SILVERFISH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SKELETON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SKELETON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SKELETON_SKULL", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "SKULL_BANNER_PATTERN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SKULL_BANNER_PATTERN", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SLIME_BALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SLIME_BALL", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "SMITHING_TEMPLATE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SMITHING_TEMPLATE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SNIFFER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SNIFFER_EGG", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SNOWBALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SNOWBALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SNOWBALL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SNOW_GOLEM", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SOUL_FIRE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SOUL_SAND", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SOUL_SOIL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SOUL_WALL_TORCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPAWNER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPAWNER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPAWNER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPECTRAL_ARROW", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPIDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPIDER_EYE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPIDER_EYE", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    Family(
        Category.TOOLS_AND_UTILITIES, "SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SPLASH_POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPLASH_POTION", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPLASH_POTION", 0),
    # Utility Tools
    Family(Category.TOOLS_AND_UTILITIES, "SPYGLASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPYGLASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPYGLASS", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SPYGLASS", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SQUID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STONE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRAY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRIDER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRING", 0),
    # Technical
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_VOID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_VOID", 0),
    Family(Category.TOOLS_AND_UTILITIES, "STRUCTURE_VOID", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "SUGAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SUGAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SUGAR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SUGAR_CANE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SULFUR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SULFUR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "SULFUR_CUBE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TADPOLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TADPOLE", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "TADPOLE_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TADPOLE_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TEST_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TEST_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TEST_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TEST_INSTANCE_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TEST_INSTANCE_BLOCK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TEST_INSTANCE_BLOCK", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "TIDE_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TIPPED_ARROW", 0),
    # Minecarts
    Family(Category.TOOLS_AND_UTILITIES, "TNT_MINECART", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TNT_MINECART", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TOTEM", 0),
    # Special
    Family(Category.TOOLS_AND_UTILITIES, "TOTEM_OF_UNDYING", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TOTEM_OF_UNDYING", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TRADER_LLAMA", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TRIAL_KEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TRIAL_KEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TRIAL_KEY", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TRIDENT", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TROPICAL_FISH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TROPICAL_FISH", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "TROPICAL_FISH_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TROPICAL_FISH_BUCKET", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE_SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "TURTLE_SCUTE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VEX", 0),
    # Patterns & Templates
    Family(Category.TOOLS_AND_UTILITIES, "VEX_ARMOR_TRIM_SMITHING_TEMPLATE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VEX_ARMOR_TRIM_SMITHING_TEMPLATE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "VILLAGER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VINDICATOR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VOID_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VOID_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "VOID_AIR", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WALL_HANGING_SIGN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WALL_SIGN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WALL_TORCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WANDERING_TRADER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WARDEN", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "WARD_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "WARPED_FUNGUS_ON_A_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WARPED_FUNGUS_ON_A_STICK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WATER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WATER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WATER", 0),
    # Buckets & Containers
    Family(Category.TOOLS_AND_UTILITIES, "WATER_BUCKET", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WATER_BUCKET", 0),
    # Patterns & Templates
    Family(
        Category.TOOLS_AND_UTILITIES, "WILD_ARMOR_TRIM_SMITHING_TEMPLATE", 0
    ),
    # Special
    Family(Category.TOOLS_AND_UTILITIES, "WIND_CHARGE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WIND_CHARGE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WIND_CHARGE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WIND_CHARGE", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "WITCH", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WITHER", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WITHER_SKELETON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WITHER_SKELETON", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WITHER_SKELETON_SKULL", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WOLF", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WOLF", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WOLF", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WOLF", 0),
    # Books & Maps
    Family(Category.TOOLS_AND_UTILITIES, "WRITABLE_BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WRITABLE_BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WRITTEN_BOOK", 0),
    Family(Category.TOOLS_AND_UTILITIES, "WRITTEN_BOOK", 0),
    # Miscellaneous
    Family(Category.TOOLS_AND_UTILITIES, "ZOGLIN", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ZOMBIE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ZOMBIE", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ZOMBIE_HEAD", 0),
    Family(Category.TOOLS_AND_UTILITIES, "ZOMBIFIED_PIGLIN", 0),
    # Combat
    # Melee Weapons
    Family(Category.COMBAT, "MACE", 0),
    Family(Category.COMBAT, "MACE", 0),
    Family(Category.COMBAT, "SPEAR", 0),
    Family(Category.COMBAT, "SPEAR", 0),
    Family(Category.COMBAT, "SWORD", 0),
    Family(Category.COMBAT, "TRIDENT", 0),
    Family(Category.COMBAT, "TRIDENT", 0),
    # Ranged Weapons
    Family(Category.COMBAT, "ARROW", 0),
    Family(Category.COMBAT, "BOW", 0),
    Family(Category.COMBAT, "CROSSBOW", 0),
    Family(Category.COMBAT, "SPECTRAL_ARROW", 0),
    Family(Category.COMBAT, "TIPPED_ARROW", 0),
    # Armor & Protection
    Family(Category.COMBAT, "CHAINMAIL", 0),
    Family(Category.COMBAT, "COPPER", 0),
    Family(Category.COMBAT, "DIAMOND", 0),
    Family(Category.COMBAT, "GOLDEN", 0),
    Family(Category.COMBAT, "HORSE", 0),
    Family(Category.COMBAT, "HORSE_ARMOR", 0),
    Family(Category.COMBAT, "IRON", 0),
    Family(Category.COMBAT, "LEATHER", 0),
    Family(Category.COMBAT, "NAUTILUS", 0),
    Family(Category.COMBAT, "NAUTILUS_ARMOR", 0),
    Family(Category.COMBAT, "NETHERITE", 0),
    Family(Category.COMBAT, "STONE", 0),
    Family(Category.COMBAT, "TURTLE", 0),
    Family(Category.COMBAT, "WOLF", 0),
    Family(Category.COMBAT, "WOODEN", 0),
    # Special Combat
    Family(Category.COMBAT, "ELYTRA", 0),
    Family(Category.COMBAT, "SHIELD", 0),
    Family(Category.COMBAT, "TOTEM_OF_UNDYING", 0),
    # Food And Drinks
    # Meat & Fish
    Family(Category.FOOD_AND_DRINKS, "BEEF", 0),
    Family(Category.FOOD_AND_DRINKS, "CHICKEN", 0),
    Family(Category.FOOD_AND_DRINKS, "COD", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_BEEF", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_CHICKEN", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_COD", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_MUTTON", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_PORKCHOP", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_RABBIT", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKED_SALMON", 0),
    Family(Category.FOOD_AND_DRINKS, "MUTTON", 0),
    Family(Category.FOOD_AND_DRINKS, "PORKCHOP", 0),
    Family(Category.FOOD_AND_DRINKS, "RABBIT", 0),
    Family(Category.FOOD_AND_DRINKS, "SALMON", 0),
    Family(Category.FOOD_AND_DRINKS, "TROPICAL_FISH", 0),
    # Plants & Prepared Foods
    Family(Category.FOOD_AND_DRINKS, "BAKED_POTATO", 0),
    Family(Category.FOOD_AND_DRINKS, "BEETROOT", 0),
    Family(Category.FOOD_AND_DRINKS, "BEETROOTS", 0),
    Family(Category.FOOD_AND_DRINKS, "BEETROOT_SOUP", 0),
    Family(Category.FOOD_AND_DRINKS, "BREAD", 0),
    Family(Category.FOOD_AND_DRINKS, "CAKE", 0),
    Family(Category.FOOD_AND_DRINKS, "CARROT", 0),
    Family(Category.FOOD_AND_DRINKS, "CARROTS", 0),
    Family(Category.FOOD_AND_DRINKS, "CARVED_PUMPKIN", 0),
    Family(Category.FOOD_AND_DRINKS, "COOKIE", 0),
    Family(Category.FOOD_AND_DRINKS, "GLOW_BERRIES", 0),
    Family(Category.FOOD_AND_DRINKS, "GOLDEN_CARROT", 0),
    Family(Category.FOOD_AND_DRINKS, "MELON_SLICE", 0),
    Family(Category.FOOD_AND_DRINKS, "MELON_STEM", 0),
    Family(Category.FOOD_AND_DRINKS, "MUSHROOM_STEW", 0),
    Family(Category.FOOD_AND_DRINKS, "POISONOUS_POTATO", 0),
    Family(Category.FOOD_AND_DRINKS, "POTATO", 0),
    Family(Category.FOOD_AND_DRINKS, "PUMPKIN_PIE", 0),
    Family(Category.FOOD_AND_DRINKS, "PUMPKIN_STEM", 0),
    Family(Category.FOOD_AND_DRINKS, "RABBIT_STEW", 0),
    Family(Category.FOOD_AND_DRINKS, "SUSPICIOUS_STEW", 0),
    Family(Category.FOOD_AND_DRINKS, "SWEET_BERRIES", 0),
    # Special Foods
    Family(Category.FOOD_AND_DRINKS, "APPLE", 0),
    Family(Category.FOOD_AND_DRINKS, "CHORUS_FRUIT", 0),
    Family(Category.FOOD_AND_DRINKS, "DRIED_KELP", 0),
    Family(Category.FOOD_AND_DRINKS, "EGG", 0),
    Family(Category.FOOD_AND_DRINKS, "GOLDEN_APPLE", 0),
    Family(Category.FOOD_AND_DRINKS, "HONEY_BOTTLE", 0),
    Family(Category.FOOD_AND_DRINKS, "MILK_BUCKET", 0),
    Family(Category.FOOD_AND_DRINKS, "POPPED_CHORUS_FRUIT", 0),
    # Ingredients
    # Minerals & Metals
    Family(Category.INGREDIENTS, "AMETHYST_SHARD", 0),
    Family(Category.INGREDIENTS, "AMETHYST_SHARD", 0),
    Family(Category.INGREDIENTS, "ANCIENT_DEBRIS", 0),
    Family(Category.INGREDIENTS, "CHARCOAL", 0),
    Family(Category.INGREDIENTS, "COAL", 0),
    Family(Category.INGREDIENTS, "COPPER_INGOT", 0),
    Family(Category.INGREDIENTS, "COPPER_NUGGET", 0),
    Family(Category.INGREDIENTS, "DIAMOND", 0),
    Family(Category.INGREDIENTS, "EMERALD", 0),
    Family(Category.INGREDIENTS, "GOLD_INGOT", 0),
    Family(Category.INGREDIENTS, "GOLD_NUGGET", 0),
    Family(Category.INGREDIENTS, "IRON_INGOT", 0),
    Family(Category.INGREDIENTS, "IRON_NUGGET", 0),
    Family(Category.INGREDIENTS, "LAPIS_LAZULI", 0),
    Family(Category.INGREDIENTS, "NETHERITE_INGOT", 0),
    Family(Category.INGREDIENTS, "NETHERITE_SCRAP", 0),
    Family(Category.INGREDIENTS, "QUARTZ", 0),
    Family(Category.INGREDIENTS, "REDSTONE", 0),
    # Mob & Crafting Ingredients
    Family(Category.INGREDIENTS, "BLAZE_POWDER", 0),
    Family(Category.INGREDIENTS, "BLAZE_ROD", 0),
    Family(Category.INGREDIENTS, "BONE", 0),
    Family(Category.INGREDIENTS, "BONE_MEAL", 0),
    Family(Category.INGREDIENTS, "BREEZE_ROD", 0),
    Family(Category.INGREDIENTS, "BRICK", 0),
    Family(Category.INGREDIENTS, "CLAY_BALL", 0),
    Family(Category.INGREDIENTS, "FEATHER", 0),
    Family(Category.INGREDIENTS, "GHAST_TEAR", 0),
    Family(Category.INGREDIENTS, "GLOW_INK_SAC", 0),
    Family(Category.INGREDIENTS, "GUNPOWDER", 0),
    Family(Category.INGREDIENTS, "INK_SAC", 0),
    Family(Category.INGREDIENTS, "LEATHER", 0),
    Family(Category.INGREDIENTS, "MAGMA_CREAM", 0),
    Family(Category.INGREDIENTS, "NAUTILUS_SHELL", 0),
    Family(Category.INGREDIENTS, "NETHER_STAR", 0),
    Family(Category.INGREDIENTS, "PHANTOM_MEMBRANE", 0),
    Family(Category.INGREDIENTS, "RABBIT_HIDE", 0),
    Family(Category.INGREDIENTS, "ROTTEN_FLESH", 0),
    Family(Category.INGREDIENTS, "SHULKER_SHELL", 0),
    Family(Category.INGREDIENTS, "SLIME_BALL", 0),
    Family(Category.INGREDIENTS, "SPIDER_EYE", 0),
    Family(Category.INGREDIENTS, "STICK", 0),
    Family(Category.INGREDIENTS, "STRING", 0),
    Family(Category.INGREDIENTS, "SUGAR", 0),
    Family(Category.INGREDIENTS, "WHEAT", 0),
    Family(Category.INGREDIENTS, "WHEAT_SEEDS", 0),
    # Books & Paper
    Family(Category.INGREDIENTS, "BOOK", 0),
    Family(Category.INGREDIENTS, "BOOKSHELF", 0),
    Family(Category.INGREDIENTS, "ENCHANTED_BOOK", 0),
    Family(Category.INGREDIENTS, "PAPER", 0),
    Family(Category.INGREDIENTS, "WRITABLE_BOOK", 0),
    Family(Category.INGREDIENTS, "WRITTEN_BOOK", 0),
    # Templates & Patterns
    Family(Category.INGREDIENTS, "BANNER_PATTERN", 0),
    Family(Category.INGREDIENTS, "SMITHING", 0),
    Family(Category.INGREDIENTS, "SMITHING_TEMPLATE", 0),
    # Pottery
    Family(Category.INGREDIENTS, "POTTERY", 0),
    Family(Category.INGREDIENTS, "POTTERY_SHERD", 0),
    # Brewing & Miscellaneous
    Family(Category.INGREDIENTS, "APPLE", 0),
    Family(Category.INGREDIENTS, "ARMADILLO_SCUTE", 0),
    Family(Category.INGREDIENTS, "BEETROOT", 0),
    Family(Category.INGREDIENTS, "BEETROOT_SEEDS", 0),
    Family(Category.INGREDIENTS, "BOWL", 0),
    Family(Category.INGREDIENTS, "BROWN_MUSHROOM", 0),
    Family(Category.INGREDIENTS, "BUNDLE", 0),
    Family(Category.INGREDIENTS, "CARROT", 0),
    Family(Category.INGREDIENTS, "CHORUS_FRUIT", 0),
    Family(Category.INGREDIENTS, "CINNABAR", 0),
    Family(Category.INGREDIENTS, "COCOA_BEANS", 0),
    Family(Category.INGREDIENTS, "DRAGON_BREATH", 0),
    Family(Category.INGREDIENTS, "DRIED_KELP", 0),
    Family(Category.INGREDIENTS, "ECHO_SHARD", 0),
    Family(Category.INGREDIENTS, "EGG", 0),
    Family(Category.INGREDIENTS, "ENDER_EYE", 0),
    Family(Category.INGREDIENTS, "ENDER_PEARL", 0),
    Family(Category.INGREDIENTS, "END_ROD", 0),
    Family(Category.INGREDIENTS, "FERMENTED_SPIDER_EYE", 0),
    Family(Category.INGREDIENTS, "FIREWORK_STAR", 0),
    Family(Category.INGREDIENTS, "FLINT", 0),
    Family(Category.INGREDIENTS, "GLASS_BOTTLE", 0),
    Family(Category.INGREDIENTS, "GLISTERING_MELON_SLICE", 0),
    Family(Category.INGREDIENTS, "GLOWSTONE_DUST", 0),
    Family(Category.INGREDIENTS, "GLOW_BERRIES", 0),
    Family(Category.INGREDIENTS, "GOLDEN_DANDELION", 0),
    Family(Category.INGREDIENTS, "HEART_OF_THE_SEA", 0),
    Family(Category.INGREDIENTS, "HEAVY_CORE", 0),
    Family(Category.INGREDIENTS, "HONEYCOMB", 0),
    Family(Category.INGREDIENTS, "HONEY_BOTTLE", 0),
    Family(Category.INGREDIENTS, "KELP", 0),
    Family(Category.INGREDIENTS, "MELON", 0),
    Family(Category.INGREDIENTS, "MELON_SEEDS", 0),
    Family(Category.INGREDIENTS, "MUSHROOM", 0),
    Family(Category.INGREDIENTS, "NETHER_BRICK", 0),
    Family(Category.INGREDIENTS, "NETHER_WART", 0),
    Family(Category.INGREDIENTS, "OMINOUS_TRIAL_KEY", 0),
    Family(Category.INGREDIENTS, "PITCHER_POD", 0),
    Family(Category.INGREDIENTS, "POPPED_CHORUS_FRUIT", 0),
    Family(Category.INGREDIENTS, "POTATO", 0),
    Family(Category.INGREDIENTS, "PRISMARINE_CRYSTALS", 0),
    Family(Category.INGREDIENTS, "PRISMARINE_SHARD", 0),
    Family(Category.INGREDIENTS, "PUMPKIN", 0),
    Family(Category.INGREDIENTS, "PUMPKIN_SEEDS", 0),
    Family(Category.INGREDIENTS, "RABBIT_FOOT", 0),
    Family(Category.INGREDIENTS, "RAW_COPPER", 0),
    Family(Category.INGREDIENTS, "RAW_GOLD", 0),
    Family(Category.INGREDIENTS, "RAW_IRON", 0),
    Family(Category.INGREDIENTS, "RED_MUSHROOM", 0),
    Family(Category.INGREDIENTS, "RESIN_CLUMP", 0),
    Family(Category.INGREDIENTS, "SEEDS", 0),
    Family(Category.INGREDIENTS, "SNOWBALL", 0),
    Family(Category.INGREDIENTS, "SULFUR", 0),
    Family(Category.INGREDIENTS, "SULFUR_CUBE_BUCKET", 0),
    Family(Category.INGREDIENTS, "SWEET_BERRIES", 0),
    Family(Category.INGREDIENTS, "TORCHFLOWER_SEEDS", 0),
    Family(Category.INGREDIENTS, "TRIAL_KEY", 0),
    Family(Category.INGREDIENTS, "TURTLE_SCUTE", 0),
    Family(Category.INGREDIENTS, "WIND_CHARGE", 0),
    # Spawn Eggs
    # Passive & Neutral
    Family(Category.SPAWN_EGGS, "ALLAY", 0),
    Family(Category.SPAWN_EGGS, "ARMADILLO", 0),
    Family(Category.SPAWN_EGGS, "BAT", 0),
    Family(Category.SPAWN_EGGS, "BEE", 0),
    Family(Category.SPAWN_EGGS, "CAMEL", 0),
    Family(Category.SPAWN_EGGS, "CAT", 0),
    Family(Category.SPAWN_EGGS, "CHICKEN", 0),
    Family(Category.SPAWN_EGGS, "COW", 0),
    Family(Category.SPAWN_EGGS, "DONKEY", 0),
    Family(Category.SPAWN_EGGS, "FOX", 0),
    Family(Category.SPAWN_EGGS, "FROG", 0),
    Family(Category.SPAWN_EGGS, "GOAT", 0),
    Family(Category.SPAWN_EGGS, "HAPPY_GHAST", 0),
    Family(Category.SPAWN_EGGS, "HORSE", 0),
    Family(Category.SPAWN_EGGS, "IRON_GOLEM", 0),
    Family(Category.SPAWN_EGGS, "LLAMA", 0),
    Family(Category.SPAWN_EGGS, "MOOSHROOM", 0),
    Family(Category.SPAWN_EGGS, "MULE", 0),
    Family(Category.SPAWN_EGGS, "OCELOT", 0),
    Family(Category.SPAWN_EGGS, "PANDA", 0),
    Family(Category.SPAWN_EGGS, "PARROT", 0),
    Family(Category.SPAWN_EGGS, "SHEEP", 0),
    Family(Category.SPAWN_EGGS, "SNIFFER", 0),
    Family(Category.SPAWN_EGGS, "SNOW_GOLEM", 0),
    Family(Category.SPAWN_EGGS, "TRADER_LLAMA", 0),
    Family(Category.SPAWN_EGGS, "VILLAGER", 0),
    Family(Category.SPAWN_EGGS, "WANDERING_TRADER", 0),
    Family(Category.SPAWN_EGGS, "WOLF", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE_HORSE", 0),
    # Aquatic
    Family(Category.SPAWN_EGGS, "AXOLOTL", 0),
    Family(Category.SPAWN_EGGS, "COD", 0),
    Family(Category.SPAWN_EGGS, "DOLPHIN", 0),
    Family(Category.SPAWN_EGGS, "GLOW_SQUID", 0),
    Family(Category.SPAWN_EGGS, "GUARDIAN", 0),
    Family(Category.SPAWN_EGGS, "NAUTILUS", 0),
    Family(Category.SPAWN_EGGS, "PUFFERFISH", 0),
    Family(Category.SPAWN_EGGS, "SALMON", 0),
    Family(Category.SPAWN_EGGS, "SQUID", 0),
    Family(Category.SPAWN_EGGS, "TADPOLE", 0),
    Family(Category.SPAWN_EGGS, "TROPICAL_FISH", 0),
    Family(Category.SPAWN_EGGS, "TURTLE", 0),
    # Nether Mobs
    Family(Category.SPAWN_EGGS, "BLAZE", 0),
    Family(Category.SPAWN_EGGS, "GHAST", 0),
    Family(Category.SPAWN_EGGS, "HOGLIN", 0),
    Family(Category.SPAWN_EGGS, "MAGMA_CUBE", 0),
    Family(Category.SPAWN_EGGS, "PIGLIN", 0),
    Family(Category.SPAWN_EGGS, "PIGLIN_BRUTE", 0),
    Family(Category.SPAWN_EGGS, "STRIDER", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIFIED_PIGLIN", 0),
    # Undead
    Family(Category.SPAWN_EGGS, "DROWNED", 0),
    Family(Category.SPAWN_EGGS, "HUSK", 0),
    Family(Category.SPAWN_EGGS, "SKELETON", 0),
    Family(Category.SPAWN_EGGS, "SKELETON_HORSE", 0),
    Family(Category.SPAWN_EGGS, "STRAY", 0),
    Family(Category.SPAWN_EGGS, "WITHER", 0),
    Family(Category.SPAWN_EGGS, "WITHER_SKELETON", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE_VILLAGER", 0),
    # Hostile & Other
    Family(Category.SPAWN_EGGS, "BOGGED", 0),
    Family(Category.SPAWN_EGGS, "BREEZE", 0),
    Family(Category.SPAWN_EGGS, "CAMEL_HUSK", 0),
    Family(Category.SPAWN_EGGS, "CAVE_SPIDER", 0),
    Family(Category.SPAWN_EGGS, "COPPER_GOLEM", 0),
    Family(Category.SPAWN_EGGS, "CREAKING", 0),
    Family(Category.SPAWN_EGGS, "CREEPER", 0),
    Family(Category.SPAWN_EGGS, "ELDER_GUARDIAN", 0),
    Family(Category.SPAWN_EGGS, "ENDERMAN", 0),
    Family(Category.SPAWN_EGGS, "ENDERMITE", 0),
    Family(Category.SPAWN_EGGS, "ENDER_DRAGON", 0),
    Family(Category.SPAWN_EGGS, "EVOKER", 0),
    Family(Category.SPAWN_EGGS, "PARCHED", 0),
    Family(Category.SPAWN_EGGS, "PHANTOM", 0),
    Family(Category.SPAWN_EGGS, "PIG", 0),
    Family(Category.SPAWN_EGGS, "PILLAGER", 0),
    Family(Category.SPAWN_EGGS, "POLAR_BEAR", 0),
    Family(Category.SPAWN_EGGS, "RABBIT", 0),
    Family(Category.SPAWN_EGGS, "RAVAGER", 0),
    Family(Category.SPAWN_EGGS, "SHULKER", 0),
    Family(Category.SPAWN_EGGS, "SILVERFISH", 0),
    Family(Category.SPAWN_EGGS, "SPIDER", 0),
    Family(Category.SPAWN_EGGS, "VEX", 0),
    Family(Category.SPAWN_EGGS, "VINDICATOR", 0),
    Family(Category.SPAWN_EGGS, "WARDEN", 0),
    Family(Category.SPAWN_EGGS, "WITCH", 0),
    Family(Category.SPAWN_EGGS, "ZOGLIN", 0),
    Family(Category.SPAWN_EGGS, "ZOMBIE_NAUTILUS", 0),
]

VARIANTS: list[Variant] = [
    # The `order`s here reset to 0 for each exclusive variant to
    # a specific group of variants. For example, `LOG` and `STEM` cannot
    # belong to the same family, so there is no need to decide whether one
    # has a higher priority than the other.
    #
    # Wood
    Variant("LOG", Affix.SUFFIX, 0),
    Variant("STEM", Affix.SUFFIX, 0),
    Variant("WOOD", Affix.SUFFIX, 1),
    Variant("HYPHAE", Affix.SUFFIX, 1),
    Variant("STRIPPED", Affix.PREFIX, 2),
    Variant("PLANKS", Affix.SUFFIX, 3),
    # General
    Variant("STAIRS", Affix.SUFFIX, 4),
    Variant("SLAB", Affix.SUFFIX, 5),
    Variant("WALL", Affix.SUFFIX, 6),
    Variant("FENCE", Affix.SUFFIX, 7),
    Variant("FENCE_GATE", Affix.SUFFIX, 8),
    Variant("DOOR", Affix.SUFFIX, 9),
    Variant("TRAPDOOR", Affix.SUFFIX, 10),
    Variant("PRESSURE_PLATE", Affix.SUFFIX, 11),
    Variant("BUTTON", Affix.SUFFIX, 12),
    Variant("BOAT", Affix.SUFFIX, 13),
    Variant("RAFT", Affix.SUFFIX, 13),
    Variant("CHEST_BOAT", Affix.SUFFIX, 14),
    Variant("CHEST_RAFT", Affix.SUFFIX, 14),
    Variant("SIGN", Affix.SUFFIX, 15),
    Variant("HANGING_SIGN", Affix.SUFFIX, 16),
    Variant("LEAVES", Affix.SUFFIX, 17),
    Variant("SAPLING", Affix.SUFFIX, 18),
    Variant("PROPAGULE", Affix.SUFFIX, 18),
    Variant("SHELF", Affix.SUFFIX, 19),
    Variant("WALL_HANGING_SIGN", Affix.SUFFIX, 20),
    Variant("WALL_SIGN", Affix.SUFFIX, 21),
    # Deepslate
    Variant("CRACKED", Affix.PREFIX, 0),
    Variant("CHISELED", Affix.PREFIX, 0),
    # Copper
    Variant("EXPOSED", Affix.PREFIX, 0),
    Variant("WEATHERED", Affix.PREFIX, 1),
    Variant("OXIDIZED", Affix.PREFIX, 2),
    Variant("WAXED", Affix.PREFIX, 3),
    Variant("MOSAIC", Affix.SUFFIX, 0),
    Variant("SPAWN_EGG", Affix.SUFFIX, 0),
    Variant("BLOCK", Affix.SUFFIX, 0),
    Variant("POTTERY_SHERD", Affix.SUFFIX, 0),
    Variant("CHEST", Affix.SUFFIX, 0),
    Variant("BARS", Affix.SUFFIX, 0),
    Variant("BULB", Affix.SUFFIX, 0),
    Variant("CHAIN", Affix.SUFFIX, 0),
    Variant("GRATE", Affix.SUFFIX, 0),
    Variant("LANTERN", Affix.SUFFIX, 0),
    Variant("TORCH", Affix.SUFFIX, 0),
    Variant("WALL_TORCH", Affix.SUFFIX, 0),
    Variant("LIGHTNING_ROD", Affix.SUFFIX, 0),
    Variant("PANE", Affix.SUFFIX, 0),
    Variant("BANNER", Affix.SUFFIX, 0),
    Variant("WALL_BANNER", Affix.SUFFIX, 0),
    Variant("BED", Affix.SUFFIX, 0),
    Variant("CANDLE", Affix.SUFFIX, 0),
    Variant("CANDLE_CAKE", Affix.SUFFIX, 0),
    Variant("CARPET", Affix.SUFFIX, 0),
    Variant("CONCRETE", Affix.SUFFIX, 0),
    Variant("CONCRETE_POWDER", Affix.SUFFIX, 0),
    Variant("GLAZED_TERRACOTTA", Affix.SUFFIX, 0),
    Variant("HARNESS", Affix.SUFFIX, 0),
    Variant("SHULKER_BOX", Affix.SUFFIX, 0),
    Variant("STAINED_GLASS", Affix.SUFFIX, 0),
    Variant("STAINED_GLASS_PANE", Affix.SUFFIX, 0),
    Variant("ORE", Affix.SUFFIX, 0),
    Variant("TERRACOTTA", Affix.SUFFIX, 0),
    Variant("WOOL", Affix.SUFFIX, 0),
    Variant("CORAL", Affix.SUFFIX, 0),
    Variant("CORAL_BLOCK", Affix.SUFFIX, 0),
    Variant("FAN", Affix.SUFFIX, 0),
    Variant("WALL_FAN", Affix.SUFFIX, 0),
    Variant("MUSHROOM_BLOCK", Affix.SUFFIX, 0),
    Variant("VINES", Affix.SUFFIX, 0),
    Variant("VINES_PLANT", Affix.SUFFIX, 0),
    Variant("FUNGUS", Affix.SUFFIX, 0),
    Variant("NYLIUM", Affix.SUFFIX, 0),
    Variant("ROOTS", Affix.SUFFIX, 0),
    Variant("WART_BLOCK", Affix.SUFFIX, 0),
    Variant("FROGLIGHT", Affix.SUFFIX, 0),
    Variant("CAULDRON", Affix.SUFFIX, 0),
    Variant("PILLAR", Affix.SUFFIX, 0),
    Variant("ORE", Affix.SUFFIX, 0),
    Variant("PLANT", Affix.SUFFIX, 0),
    Variant("CROP", Affix.SUFFIX, 0),
    Variant("SEEDS", Affix.SUFFIX, 0),
    Variant("BUSH", Affix.SUFFIX, 0),
    # Rails
    Variant("ACTIVATOR", Affix.PREFIX, 0),
    Variant("DETECTOR", Affix.PREFIX, 0),
    Variant("POWERED", Affix.PREFIX, 0),
    # Amethyst
    Variant("BUDDING", Affix.PREFIX, 0),
    Variant("CLUSTER", Affix.SUFFIX, 0),
    # Colored
    Variant("WHITE", Affix.PREFIX, 0),
    Variant("LIGHT_GRAY", Affix.PREFIX, 1),
    Variant("GRAY", Affix.PREFIX, 2),
    Variant("BLACK", Affix.PREFIX, 3),
    Variant("BROWN", Affix.PREFIX, 4),
    Variant("RED", Affix.PREFIX, 5),
    Variant("ORANGE", Affix.PREFIX, 6),
    Variant("YELLOW", Affix.PREFIX, 7),
    Variant("LIME", Affix.PREFIX, 8),
    Variant("GREEN", Affix.PREFIX, 9),
    Variant("CYAN", Affix.PREFIX, 10),
    Variant("LIGHT_BLUE", Affix.PREFIX, 11),
    Variant("BLUE", Affix.PREFIX, 12),
    Variant("PURPLE", Affix.PREFIX, 13),
    Variant("MAGENTA", Affix.PREFIX, 14),
    Variant("PINK", Affix.PREFIX, 15),
    # Pottery
    Variant("ANGLER", Affix.PREFIX, 0),
    Variant("ARCHER", Affix.PREFIX, 0),
    Variant("ARMS_UP", Affix.PREFIX, 0),
    Variant("BLADE", Affix.PREFIX, 0),
    Variant("BREWER", Affix.PREFIX, 0),
    Variant("BURN", Affix.PREFIX, 0),
    Variant("DANGER", Affix.PREFIX, 0),
    Variant("EXPLORER", Affix.PREFIX, 0),
    Variant("FLOW", Affix.PREFIX, 0),
    Variant("FRIEND", Affix.PREFIX, 0),
    Variant("GUSTER", Affix.PREFIX, 0),
    Variant("HEART", Affix.PREFIX, 0),
    Variant("HEARTBREAK", Affix.PREFIX, 0),
    Variant("HOWL", Affix.PREFIX, 0),
    Variant("MINER", Affix.PREFIX, 0),
    Variant("MOURNER", Affix.PREFIX, 0),
    Variant("PLENTY", Affix.PREFIX, 0),
    Variant("PRIZE", Affix.PREFIX, 0),
    Variant("SCRAPE", Affix.PREFIX, 0),
    Variant("SHEAF", Affix.PREFIX, 0),
    Variant("SHELTER", Affix.PREFIX, 0),
    Variant("SKULL", Affix.PREFIX, 0),
    Variant("SNORT", Affix.PREFIX, 0),
    # Melon
    Variant("ATTACHED", Affix.PREFIX, 0),
    # Armor
    Variant("BOOTS", Affix.SUFFIX, 0),
    Variant("CHESTPLATE", Affix.SUFFIX, 0),
    Variant("LEGGINGS", Affix.SUFFIX, 0),
    Variant("HELMET", Affix.SUFFIX, 0),
    # Tools
    Variant("LEATHER", Affix.PREFIX, 0),
    Variant("WOODEN", Affix.PREFIX, 0),
    Variant("STONE", Affix.PREFIX, 0),
    Variant("COPPER", Affix.PREFIX, 0),
    Variant("IRON", Affix.PREFIX, 0),
    Variant("GOLDEN", Affix.PREFIX, 0),
    Variant("DIAMOND", Affix.PREFIX, 0),
    Variant("NETHERITE", Affix.PREFIX, 0),
    # Heads
    Variant("WALL_SKULL", Affix.SUFFIX, 0),
    Variant("WALL_HEAD", Affix.SUFFIX, 0),
    # Anvil
    Variant("CHIPPED", Affix.PREFIX, 0),
    Variant("DAMAGED", Affix.PREFIX, 0),
    # Silk-touched Ores
    Variant("STONE", Affix.PREFIX, 0),
    Variant("DEEPSLATE", Affix.PREFIX, 0),
    Variant("NETHER", Affix.PREFIX, 0),
    # Disc
    Variant("11", Affix.SUFFIX, 0),
    Variant("13", Affix.SUFFIX, 0),
    Variant("5", Affix.SUFFIX, 0),
    Variant("BLOCKS", Affix.SUFFIX, 0),
    Variant("BOUNCE", Affix.SUFFIX, 0),
    Variant("CAT", Affix.SUFFIX, 0),
    Variant("CHIRP", Affix.SUFFIX, 0),
    Variant("CREATOR", Affix.SUFFIX, 0),
    Variant("CREATOR_MUSIC_BOX", Affix.SUFFIX, 0),
    Variant("FAR", Affix.SUFFIX, 0),
    Variant("LAVA_CHICKEN", Affix.SUFFIX, 0),
    Variant("MALL", Affix.SUFFIX, 0),
    Variant("MELLOHI", Affix.SUFFIX, 0),
    Variant("OTHERSIDE", Affix.SUFFIX, 0),
    Variant("PIGSTEP", Affix.SUFFIX, 0),
    Variant("PRECIPICE", Affix.SUFFIX, 0),
    Variant("RELIC", Affix.SUFFIX, 0),
    Variant("STAL", Affix.SUFFIX, 0),
    Variant("STRAD", Affix.SUFFIX, 0),
    Variant("TEARS", Affix.SUFFIX, 0),
    Variant("WAIT", Affix.SUFFIX, 0),
    Variant("WARD", Affix.SUFFIX, 0),
    # Banner Pattern
    Variant("BORDURE_INDENTED", Affix.PREFIX, 0),
    Variant("CREEPER", Affix.PREFIX, 0),
    Variant("FIELD_MASONED", Affix.PREFIX, 0),
    Variant("FLOW", Affix.PREFIX, 0),
    Variant("FLOWER", Affix.PREFIX, 0),
    Variant("GLOBE", Affix.PREFIX, 0),
    Variant("GUSTER", Affix.PREFIX, 0),
    Variant("MOJANG", Affix.PREFIX, 0),
    Variant("PIGLIN", Affix.PREFIX, 0),
    Variant("SKULL", Affix.PREFIX, 0),
    Variant("INFESTED", Affix.PREFIX, 0),
    # Froglight
    Variant("OCHRE", Affix.PREFIX, 0),
    Variant("PEARLESCENT", Affix.PREFIX, 0),
    Variant("VERDANT", Affix.PREFIX, 0),
    # Armor Trims
    Variant("NETHERITE_UPGRADE", Affix.PREFIX, 0),
    Variant("BOLT_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("COAST_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("DUNE_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("EYE_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("FLOW_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("HOST_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("RAISER_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("RIB_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("SENTRY_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("SHAPER_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("SILENCE_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("SNOUT_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("SPIRE_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("TIDE_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("VEX_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("WARD_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("WAYFINDER_ARMOR_TRIM", Affix.PREFIX, 0),
    Variant("WILD_ARMOR_TRIM", Affix.PREFIX, 0),
]
